/* hl-sample.js — GENERATED by tools/import_hilo.js. Do not edit.
 *
 * Three real boards and the two calendar days they stand on: what the Worker
 * falls back to with no database bound, and what the suites play. The bank
 * lives outside the repository; this is a sample of it, and small on purpose
 * so committing the bank by accident would show in a diff. */
export const HL_SAMPLE_BOARDS = [
 {
  "id": "398",
  "category": "Clubs by year formed",
  "subtitle": "The year the club was founded, under whatever name it started with.",
  "unit": "year",
  "valueClass": "fixed-by-nature",
  "trueAsOf": "2026-09-02",
  "chain": [
   {
    "name": "Wrexham",
    "value": 1864,
    "context": "Formed by Wrexham Cricket Club members at the Turf Hotel",
    "source": {
     "publisher": "Wrexham",
     "url": "https://www.wrexhamafc.co.uk/the-club/history-and-honours",
     "quote": "Wrexham AFC was founded in 1864, making it Wales' oldest professional Football Club and the third oldest in the world.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Barnsley",
    "value": 1887,
    "context": "Reverend Tiverton Preedy's Barnsley St. Peter's",
    "source": {
     "publisher": "Barnsley",
     "url": "https://www.barnsleyfc.co.uk/club/history/through-the-years",
     "quote": "The club was founded in 1887 by Reverend Tiverton Preedy, initially named Barnsley St. Peter's.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Southampton",
    "value": 1885,
    "context": "Formed by the St Mary's Church Young Men's Association",
    "source": {
     "publisher": "Southampton",
     "url": "https://www.southamptonfc.com/en/st-marys-fc",
     "quote": "The Saints were formed at a meeting of the St Mary's Church of England Young Men's Association sometime in November 1885.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Bradford City",
    "value": 1903,
    "context": "Forerunner Manningham FC played rugby at Valley Parade",
    "source": {
     "publisher": "Bradford City",
     "url": "https://www.bradfordcityafc.com/club/history/club-history",
     "quote": "1903: Manningham FC convert to football from rugby, secure election to the Football League and recruit players for a new team - 'Bradford City AFC'",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Charlton Athletic",
    "value": 1905,
    "context": "Formed by teenagers who played in East Street",
    "source": {
     "publisher": "Charlton Athletic",
     "url": "https://www.cafc.co.uk/history/mens-club-history/1905-1923-early-days",
     "quote": "On June 9th, 1905, a group of teenagers who once kicked a ball around that very street decided to get together and form a fully-fledged football club that was to become Charlton Athletic.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Brentford",
    "value": 1889,
    "context": "Formed at the Oxford and Cambridge Public House",
    "source": {
     "publisher": "Brentford",
     "url": "https://www.brentfordfc.com/en/history",
     "quote": "The formation of Brentford Football Club in 1889 is owed to the decision by the Brentford Local Board [a forerunner of today's councils] to open a new Recreation Ground in the town.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Stockport County",
    "value": 1883,
    "context": "Heaton Norris Rovers, the Hatters of Edgeley Park",
    "source": {
     "publisher": "Stockport County",
     "url": "https://www.stockportcounty.com/club/history/story",
     "quote": "Established in 1883 as Heaton Norris Rovers, in 1890 the name was changed to Stockport County to reflect the town gaining County Borough status.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "West Bromwich Albion",
    "value": 1878,
    "context": "Began as West Bromwich Strollers",
    "source": {
     "publisher": "West Bromwich Albion",
     "url": "https://www.wba.co.uk/club/history/club-history",
     "quote": "The club that became West Bromwich Albion was formed in 1878 by a group of young workers at the George Salter Springs factory, appropriate for a club whose terrace celebration would more than a century later become \"boing boing\".",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "West Ham United",
    "value": 1895,
    "context": "Began as Thames Ironworks, the shipyard's team",
    "source": {
     "publisher": "West Ham United",
     "url": "https://www.whufc.com/en/the-club/history/club-history/1890s",
     "quote": "In June 1895, the formation of the senior works football club was announced in the company's 'Thames Iron Works Gazette' newspaper and Taylor set about assembling a squad and arranging friendly matches for the 1895/96 season.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Aston Villa",
    "value": 1874,
    "context": "Four men from the chapel Bible class, under a gas lamp",
    "source": {
     "publisher": "Aston Villa",
     "url": "https://www.avfc.co.uk/history/timeline",
     "quote": "Four gentlemen stood under a gas lamp in Heathfield Road in 1874 and engaged in a discussion which would create one of the greatest clubs in the world.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Leicester City",
    "value": 1884,
    "context": "Known as Leicester Fosse until 1919",
    "source": {
     "publisher": "Leicester City",
     "url": "https://www.lcfc.com/history",
     "quote": "Formed in 1884, Leicester City Football Club, formerly known as Leicester Fosse until 1919, have won every major honour in English football.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Colchester United",
    "value": 1937,
    "context": "Layer Road, then the JobServe Community Stadium",
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/Colchester_United_F.C.",
     "quote": "Founded in 1937, the club spent its early years playing in the Southern Football League until they were elected to the Football League in 1950.",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/founding-colchester-united-secondary.html"
    },
    "sourceNote": "the club's own site states no founding year; taken from the league's official club page"
   }
  ],
  "direction": {
   "higher": "Later",
   "lower": "Earlier"
  },
  "sourceLine": "Source: each club's own official website, opened 2 September 2026. Leeds from the Premier League's club page."
 },
 {
  "id": "399",
  "category": "England caps",
  "subtitle": "Senior England appearances. Retired players only, so nothing moves.",
  "unit": "count",
  "valueClass": "retired-only",
  "trueAsOf": "2026-09-02",
  "chain": [
   {
    "name": "Chris Woods",
    "value": 43,
    "context": "Goalkeeper, England debut 1985",
    "retired": true,
    "detail": {
     "nameRaw": "Chris Woods",
     "born": null,
     "debutYear": 1985,
     "caps": 43,
     "goals": 0
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Chris Woods GK 43 0 16 June 1985 United States 9 June 1993 United States [174][175]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Joe Hart",
    "value": 75,
    "context": "Goalkeeper, England debut 2008",
    "retired": true,
    "detail": {
     "nameRaw": "Joe Hart",
     "born": null,
     "debutYear": 2008,
     "caps": 75,
     "goals": 0
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Joe Hart GK 75 0 1 June 2008 Trinidad and Tobago 14 November 2017 Brazil [70][71]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Sol Campbell",
    "value": 73,
    "context": "Defender, England debut 1996",
    "retired": true,
    "detail": {
     "nameRaw": "Sol Campbell",
     "born": null,
     "debutYear": 1996,
     "caps": 73,
     "goals": 1
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Sol Campbell DF 73 1 18 May 1996 Hungary 21 November 2007 Croatia [74][75]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Emile Heskey",
    "value": 62,
    "context": "Forward, England debut 1999",
    "retired": true,
    "detail": {
     "nameRaw": "Emile Heskey",
     "born": null,
     "debutYear": 1999,
     "caps": 62,
     "goals": 7
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Emile Heskey FW 62 7 28 April 1999 Hungary 27 June 2010 Germany [100][101]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "James Milner",
    "value": 61,
    "context": "Midfielder / Defender, England debut 2009",
    "retired": true,
    "detail": {
     "nameRaw": "James Milner",
     "born": null,
     "debutYear": 2009,
     "caps": 61,
     "goals": 1
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "James Milner MF / DF 61 1 12 August 2009 Netherlands 11 June 2016 Russia [104][105]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "John Terry",
    "value": 78,
    "context": "Defender, England debut 2003",
    "retired": true,
    "detail": {
     "nameRaw": "John Terry",
     "born": null,
     "debutYear": 2003,
     "caps": 78,
     "goals": 6
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "John Terry DF 78 6 3 June 2003 Serbia and Montenegro 7 September 2012 Moldova [60][61]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Phil Jagielka",
    "value": 40,
    "context": "Defender, England debut 2008",
    "retired": true,
    "detail": {
     "nameRaw": "Phil Jagielka",
     "born": null,
     "debutYear": 2008,
     "caps": 40,
     "goals": 3
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Phil Jagielka DF 40 3 1 June 2008 Trinidad and Tobago 15 November 2016 Spain [198][199]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Jermain Defoe",
    "value": 57,
    "context": "Forward, England debut 2004",
    "retired": true,
    "detail": {
     "nameRaw": "Jermain Defoe",
     "born": null,
     "debutYear": 2004,
     "caps": 57,
     "goals": 20
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Jermain Defoe FW 57 20 31 March 2004 Sweden 10 June 2017 Scotland [120][121]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Tony Adams",
    "value": 66,
    "context": "Defender, England debut 1987",
    "retired": true,
    "detail": {
     "nameRaw": "Tony Adams",
     "born": null,
     "debutYear": 1987,
     "caps": 66,
     "goals": 5
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Tony Adams DF 66 5 18 February 1987 Spain 7 October 2000 Germany [80][81]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Paul Ince",
    "value": 53,
    "context": "Midfielder, England debut 1992",
    "retired": true,
    "detail": {
     "nameRaw": "Paul Ince",
     "born": null,
     "debutYear": 1992,
     "caps": 53,
     "goals": 2
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Paul Ince MF 53 2 9 September 1992 Spain 20 June 2000 Romania [138][139]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Paul Robinson",
    "value": 41,
    "context": "Goalkeeper, England debut 2003",
    "retired": true,
    "detail": {
     "nameRaw": "Paul Robinson",
     "born": null,
     "debutYear": 2003,
     "caps": 41,
     "goals": 0
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Paul Robinson GK 41 0 12 February 2003 Australia 17 October 2007 Russia [196][197]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Wayne Rooney",
    "value": 120,
    "context": "Forward, England debut 2003, born 1985",
    "retired": true,
    "detail": {
     "nameRaw": "Wayne Rooney",
     "born": "24 October 1985",
     "debutYear": 2003,
     "caps": 120,
     "goals": 53
    },
    "source": {
     "publisher": "The FA (englandfootball.com)",
     "url": "https://www.englandfootball.com/england/mens-senior-team/squad/Legends-profiles/wayne-rooney",
     "quote": "Wayne Rooney won 120 caps for England between 2003 and 2018, a record for an outfield player in the history of the English national team.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   }
  ],
  "sourceLine": "Source: The FA's official England legend profiles (englandfootball.com), opened 2 September 2026."
 },
 {
  "id": "296",
  "category": "Real Madrid head coaches",
  "subtitle": "The year he first took charge, caretaker spells included. A coach with more than one spell is dated by his first.",
  "unit": "year",
  "valueClass": "fixed-by-nature",
  "trueAsOf": "2026-09-02",
  "chain": [
   {
    "name": "Luis Molowny",
    "value": 1973,
    "context": "Left in 1974, came back in 1977, 1982 and 1985",
    "detail": {
     "spells": 4,
     "renderedRange": "Luis Molowny 1973 - 1974",
     "clubRecordStart": "1974-01",
     "clubRecordEnd": "1974-05"
    },
    "source": {
     "publisher": "Real Madrid",
     "url": "https://www.realmadrid.com/en-US/the-club/history/football/first-team/coaches",
     "quote": "Luis Molowny 1973 - 1974",
     "accessed": "2026-09-02"
    }
   },
   {
    "name": "Xabi Alonso",
    "value": 2025,
    "context": "In charge until 2026",
    "detail": {
     "spells": 1,
     "renderedRange": "Xabi Alonso 2025 - 2026",
     "clubRecordStart": "2025-06-01",
     "clubRecordEnd": "2026-01-12"
    },
    "source": {
     "publisher": "Real Madrid",
     "url": "https://www.realmadrid.com/en-US/the-club/history/football/first-team/coaches",
     "quote": "Xabi Alonso 2025 - 2026",
     "accessed": "2026-09-02"
    }
   },
   {
    "name": "Zinedine Zidane",
    "value": 2016,
    "context": "Left in 2018, came back in 2019",
    "detail": {
     "spells": 2,
     "renderedRange": "Zinedine Zidane 2016 - 2018",
     "clubRecordStart": "2016-01-04",
     "clubRecordEnd": "2018-05-31"
    },
    "source": {
     "publisher": "Real Madrid",
     "url": "https://www.realmadrid.com/en-US/the-club/history/football/first-team/coaches",
     "quote": "Zinedine Zidane 2016 - 2018",
     "accessed": "2026-09-02"
    }
   },
   {
    "name": "Julen Lopetegui",
    "value": 2018,
    "context": "In charge until 2018",
    "detail": {
     "spells": 1,
     "renderedRange": "Julen Lopetegui 2018 - 2018",
     "clubRecordStart": "2018-06-14",
     "clubRecordEnd": "2018-10-28"
    },
    "source": {
     "publisher": "Real Madrid",
     "url": "https://www.realmadrid.com/en-US/the-club/history/football/first-team/coaches",
     "quote": "Julen Lopetegui 2018 - 2018",
     "accessed": "2026-09-02"
    }
   },
   {
    "name": "Carlo Ancelotti",
    "value": 2013,
    "context": "Left in 2015, came back in 2021",
    "detail": {
     "spells": 2,
     "renderedRange": "Carlo Ancelotti 2013 - 2015",
     "clubRecordStart": "2013-06-25",
     "clubRecordEnd": "2015-05-25"
    },
    "source": {
     "publisher": "Real Madrid",
     "url": "https://www.realmadrid.com/en-US/the-club/history/football/first-team/coaches",
     "quote": "Carlo Ancelotti 2013 - 2015",
     "accessed": "2026-09-02"
    }
   },
   {
    "name": "Fabio Capello",
    "value": 1996,
    "context": "Left in 1997, came back in 2006",
    "detail": {
     "spells": 2,
     "renderedRange": "Fabio Capello 1996 - 1997",
     "clubRecordStart": "1996-07",
     "clubRecordEnd": "1997-07"
    },
    "source": {
     "publisher": "Real Madrid",
     "url": "https://www.realmadrid.com/en-US/the-club/history/football/first-team/coaches",
     "quote": "Fabio Capello 1996 - 1997",
     "accessed": "2026-09-02"
    }
   },
   {
    "name": "Vicente Del Bosque",
    "value": 1994,
    "context": "Left in 1994, came back in 1995 and 1999",
    "detail": {
     "spells": 3,
     "renderedRange": "Vicente Del Bosque 1994 - 1994",
     "clubRecordStart": "1994-03",
     "clubRecordEnd": "1994-06"
    },
    "source": {
     "publisher": "Real Madrid",
     "url": "https://www.realmadrid.com/en-US/the-club/history/football/first-team/coaches",
     "quote": "Vicente Del Bosque 1994 - 1994",
     "accessed": "2026-09-02"
    }
   },
   {
    "name": "Vanderlei Luxemburgo",
    "value": 2004,
    "context": "In charge until 2005",
    "detail": {
     "spells": 1,
     "renderedRange": "Vanderlei Luxemburgo 2004 - 2005",
     "clubRecordStart": "2004-12",
     "clubRecordEnd": "2005-12"
    },
    "source": {
     "publisher": "Real Madrid",
     "url": "https://www.realmadrid.com/en-US/the-club/history/football/first-team/coaches",
     "quote": "Vanderlei Luxemburgo 2004 - 2005",
     "accessed": "2026-09-02"
    }
   },
   {
    "name": "Guus Hiddink",
    "value": 1998,
    "context": "In charge until 1999",
    "detail": {
     "spells": 1,
     "renderedRange": "Guus Hiddink 1998 - 1999",
     "clubRecordStart": "1998-06",
     "clubRecordEnd": "1999-02"
    },
    "source": {
     "publisher": "Real Madrid",
     "url": "https://www.realmadrid.com/en-US/the-club/history/football/first-team/coaches",
     "quote": "Guus Hiddink 1998 - 1999",
     "accessed": "2026-09-02"
    }
   },
   {
    "name": "John Toshack",
    "value": 1989,
    "context": "Left in 1990, came back in 1999",
    "detail": {
     "spells": 2,
     "renderedRange": "John Benjamin Toshack 1989 - 1990",
     "clubRecordStart": "1989-07",
     "clubRecordEnd": "1990-11"
    },
    "source": {
     "publisher": "Real Madrid",
     "url": "https://www.realmadrid.com/en-US/the-club/history/football/first-team/coaches",
     "quote": "John Benjamin Toshack 1989 - 1990",
     "accessed": "2026-09-02"
    }
   },
   {
    "name": "Alfredo Di Stefano",
    "value": 1982,
    "context": "Left in 1984, came back in 1990",
    "detail": {
     "spells": 2,
     "renderedRange": "Alfredo Di Stefano 1982 - 1984",
     "clubRecordStart": "1982-07",
     "clubRecordEnd": "1984-06"
    },
    "source": {
     "publisher": "Real Madrid",
     "url": "https://www.realmadrid.com/en-US/the-club/history/football/first-team/coaches",
     "quote": "Alfredo Di Stefano 1982 - 1984",
     "accessed": "2026-09-02"
    }
   },
   {
    "name": "Manuel Pellegrini",
    "value": 2009,
    "context": "In charge until 2010",
    "detail": {
     "spells": 1,
     "renderedRange": "Manuel Pellegrini 2009 - 2010",
     "clubRecordStart": "2009-06-01",
     "clubRecordEnd": "2010-05-26"
    },
    "source": {
     "publisher": "Real Madrid",
     "url": "https://www.realmadrid.com/en-US/the-club/history/football/first-team/coaches",
     "quote": "Manuel Pellegrini 2009 - 2010",
     "accessed": "2026-09-02"
    }
   }
  ],
  "direction": {
   "higher": "Later",
   "lower": "Earlier"
  },
  "sourceLine": "Source: Real Madrid official website (realmadrid.com), coaches page, opened 2 September 2026."
 }
];
export const HL_SAMPLE_SCHEDULE = {
 "2026-09-03": "398",
 "2026-09-04": "399"
};
