/* GENERATED by tools/build_scrambled.js — do not edit by hand.
 *
 * Kept under functions/ on purpose. Anything under a game's own directory is
 * served by Cloudflare Pages as a public file; this holds names, clubs and
 * aliases, so it lives where only a Worker can read it.
 *
 * Rebuild with:  node tools/build_scrambled.js
 */
export const SC_BOARDS = [
  {
    "id": 1,
    "title": "Champions League final, 1999",
    "pool": "Manchester United's starting XI at the Nou Camp, 26 May 1999. Keane and Scholes were suspended.",
    "formation": "4-4-2",
    "hintField": "nationality",
    "source": "https://en.wikipedia.org/wiki/1999_UEFA_Champions_League_final",
    "bands": [
      {
        "id": "gk",
        "y": 0.9
      },
      {
        "id": "b1",
        "y": 0.74
      },
      {
        "id": "b2",
        "y": 0.45
      },
      {
        "id": "b3",
        "y": 0.16
      }
    ],
    "slots": [
      {
        "id": "s1",
        "band": "gk",
        "x": 0.5,
        "pos": "GK",
        "name": "SCHMEICHEL",
        "aliases": [
          "PETER SCHMEICHEL"
        ],
        "club": "Manchester United",
        "nationality": "Denmark",
        "scramble": "IMSCHCHELE",
        "fixed": 0,
        "len": [
          10
        ]
      },
      {
        "id": "s2",
        "band": "b1",
        "x": 0.2,
        "pos": "LB",
        "name": "IRWIN",
        "aliases": [
          "DENIS IRWIN"
        ],
        "club": "Manchester United",
        "nationality": "Republic of Ireland",
        "scramble": "NIRWI",
        "fixed": 0,
        "len": [
          5
        ]
      },
      {
        "id": "s3",
        "band": "b1",
        "x": 0.4,
        "pos": "CB",
        "name": "JOHNSEN",
        "aliases": [
          "RONNY JOHNSEN"
        ],
        "club": "Manchester United",
        "nationality": "Norway",
        "scramble": "ENJHNOS",
        "fixed": 0,
        "len": [
          7
        ]
      },
      {
        "id": "s4",
        "band": "b1",
        "x": 0.6,
        "pos": "CB",
        "name": "STAM",
        "aliases": [
          "JAAP STAM"
        ],
        "club": "Manchester United",
        "nationality": "Netherlands",
        "scramble": "MAST",
        "fixed": 0,
        "len": [
          4
        ]
      },
      {
        "id": "s5",
        "band": "b1",
        "x": 0.8,
        "pos": "RB",
        "name": "NEVILLE",
        "aliases": [
          "GARY NEVILLE"
        ],
        "club": "Manchester United",
        "nationality": "England",
        "scramble": "LNEVEIL",
        "fixed": 0,
        "len": [
          7
        ]
      },
      {
        "id": "s6",
        "band": "b2",
        "x": 0.2,
        "pos": "LM",
        "name": "BLOMQVIST",
        "aliases": [
          "JESPER BLOMQVIST"
        ],
        "club": "Manchester United",
        "nationality": "Sweden",
        "scramble": "TQBIVSLMO",
        "fixed": 0,
        "len": [
          9
        ]
      },
      {
        "id": "s7",
        "band": "b2",
        "x": 0.4,
        "pos": "CM",
        "name": "BUTT",
        "aliases": [
          "NICKY BUTT"
        ],
        "club": "Manchester United",
        "nationality": "England",
        "scramble": "TTUB",
        "fixed": 0,
        "len": [
          4
        ]
      },
      {
        "id": "s8",
        "band": "b2",
        "x": 0.6,
        "pos": "CM",
        "name": "BECKHAM",
        "aliases": [
          "DAVID BECKHAM"
        ],
        "club": "Manchester United",
        "nationality": "England",
        "scramble": "EKAHBMC",
        "fixed": 0,
        "len": [
          7
        ]
      },
      {
        "id": "s9",
        "band": "b2",
        "x": 0.8,
        "pos": "RM",
        "name": "GIGGS",
        "aliases": [
          "RYAN GIGGS"
        ],
        "club": "Manchester United",
        "nationality": "Wales",
        "scramble": "IGSGG",
        "fixed": 1,
        "len": [
          5
        ]
      },
      {
        "id": "s10",
        "band": "b3",
        "x": 0.3333,
        "pos": "ST",
        "name": "COLE",
        "aliases": [
          "ANDY COLE",
          "ANDREW COLE"
        ],
        "club": "Manchester United",
        "nationality": "England",
        "scramble": "OECL",
        "fixed": 0,
        "len": [
          4
        ]
      },
      {
        "id": "s11",
        "band": "b3",
        "x": 0.6667,
        "pos": "ST",
        "name": "YORKE",
        "aliases": [
          "DWIGHT YORKE"
        ],
        "club": "Manchester United",
        "nationality": "Trinidad and Tobago",
        "scramble": "REOYK",
        "fixed": 0,
        "len": [
          5
        ]
      }
    ]
  },
  {
    "id": 2,
    "title": "World Cup final, 1966",
    "pool": "England's starting XI against West Germany at Wembley, 30 July 1966. Clubs are the ones they were at on the day.",
    "formation": "4-4-2",
    "hintField": "club",
    "source": "https://en.wikipedia.org/wiki/1966_FIFA_World_Cup_squads",
    "bands": [
      {
        "id": "gk",
        "y": 0.9
      },
      {
        "id": "b1",
        "y": 0.74
      },
      {
        "id": "b2",
        "y": 0.45
      },
      {
        "id": "b3",
        "y": 0.16
      }
    ],
    "slots": [
      {
        "id": "s1",
        "band": "gk",
        "x": 0.5,
        "pos": "GK",
        "name": "BANKS",
        "aliases": [
          "GORDON BANKS"
        ],
        "club": "Leicester City",
        "nationality": "England",
        "scramble": "KBSNA",
        "fixed": 0,
        "len": [
          5
        ]
      },
      {
        "id": "s2",
        "band": "b1",
        "x": 0.2,
        "pos": "LB",
        "name": "WILSON",
        "aliases": [
          "RAY WILSON"
        ],
        "club": "Everton",
        "nationality": "England",
        "scramble": "SNWLIO",
        "fixed": 0,
        "len": [
          6
        ]
      },
      {
        "id": "s3",
        "band": "b1",
        "x": 0.4,
        "pos": "CB",
        "name": "MOORE",
        "aliases": [
          "BOBBY MOORE"
        ],
        "club": "West Ham United",
        "nationality": "England",
        "scramble": "RMEOO",
        "fixed": 0,
        "len": [
          5
        ]
      },
      {
        "id": "s4",
        "band": "b1",
        "x": 0.6,
        "pos": "CB",
        "name": "JACK CHARLTON",
        "aliases": [
          "J CHARLTON"
        ],
        "club": "Leeds United",
        "nationality": "England",
        "scramble": "CONJACTLHAKR",
        "fixed": 0,
        "len": [
          4,
          8
        ]
      },
      {
        "id": "s5",
        "band": "b1",
        "x": 0.8,
        "pos": "RB",
        "name": "COHEN",
        "aliases": [
          "GEORGE COHEN"
        ],
        "club": "Fulham",
        "nationality": "England",
        "scramble": "NCEHO",
        "fixed": 0,
        "len": [
          5
        ]
      },
      {
        "id": "s6",
        "band": "b2",
        "x": 0.2,
        "pos": "LM",
        "name": "PETERS",
        "aliases": [
          "MARTIN PETERS"
        ],
        "club": "West Ham United",
        "nationality": "England",
        "scramble": "EPESTR",
        "fixed": 0,
        "len": [
          6
        ]
      },
      {
        "id": "s7",
        "band": "b2",
        "x": 0.4,
        "pos": "CM",
        "name": "STILES",
        "aliases": [
          "NOBBY STILES"
        ],
        "club": "Manchester United",
        "nationality": "England",
        "scramble": "ESLSTI",
        "fixed": 0,
        "len": [
          6
        ]
      },
      {
        "id": "s8",
        "band": "b2",
        "x": 0.6,
        "pos": "CM",
        "name": "BOBBY CHARLTON",
        "aliases": [
          "B CHARLTON"
        ],
        "club": "Manchester United",
        "nationality": "England",
        "scramble": "HCOLTBRNBYABO",
        "fixed": 0,
        "len": [
          5,
          8
        ]
      },
      {
        "id": "s9",
        "band": "b2",
        "x": 0.8,
        "pos": "RM",
        "name": "BALL",
        "aliases": [
          "ALAN BALL"
        ],
        "club": "Blackpool",
        "nationality": "England",
        "scramble": "LLAB",
        "fixed": 0,
        "len": [
          4
        ]
      },
      {
        "id": "s10",
        "band": "b3",
        "x": 0.3333,
        "pos": "ST",
        "name": "HUNT",
        "aliases": [
          "ROGER HUNT"
        ],
        "club": "Liverpool",
        "nationality": "England",
        "scramble": "UHTN",
        "fixed": 0,
        "len": [
          4
        ]
      },
      {
        "id": "s11",
        "band": "b3",
        "x": 0.6667,
        "pos": "ST",
        "name": "HURST",
        "aliases": [
          "GEOFF HURST"
        ],
        "club": "West Ham United",
        "nationality": "England",
        "scramble": "RTSUH",
        "fixed": 0,
        "len": [
          5
        ]
      }
    ]
  }
];
