/* GENERATED by tools/build_scrambled.js — do not edit by hand.
 *
 * A SAMPLE OF 4 BOARDS, NOT THE BANK. The bank is in D1 and its
 * sources live outside this repository, the same arrangement the crossword and
 * the word search use. This exists so an unbound D1 binding degrades to
 * something playable instead of to nothing.
 *
 * Kept under functions/ on purpose: Pages bundles this into the Worker rather
 * than serving it. The sources were NOT under functions/ and were being served
 * by the live site — the answer key and the schedule, on a game whose API
 * refuses to show tomorrow's board.
 *
 * Rebuild with:  node tools/build_scrambled.js
 */
export const SC_BOARDS = [
  {
    "id": 1,
    "title": "Daily XI, 4-4-2",
    "pool": "Eleven Premier League players. Not a team — nobody here lined up together.",
    "formation": "4-4-2",
    "hintField": "clubs",
    "source": "generated from research/daily/daily-roster.json; every player sourced and verified individually",
    "bands": [
      {
        "id": "gk",
        "y": 0.9
      },
      {
        "id": "b1",
        "y": 0.74
      },
      {
        "id": "b2",
        "y": 0.45
      },
      {
        "id": "b3",
        "y": 0.16
      }
    ],
    "slots": [
      {
        "id": "s1",
        "band": "gk",
        "x": 0.5,
        "pos": "GK",
        "name": "MIGNOLET",
        "display": "SIMON MIGNOLET",
        "aliases": [
          "SIMON MIGNOLET"
        ],
        "club": null,
        "nationality": "Belgium",
        "clubs": [
          {
            "club": "Sint-Truiden",
            "from": 2006,
            "to": 2010,
            "apps": 100,
            "loan": false
          },
          {
            "club": "Sunderland",
            "from": 2010,
            "to": 2013,
            "apps": 90,
            "loan": false
          },
          {
            "club": "Liverpool",
            "from": 2013,
            "to": 2019,
            "apps": 155,
            "loan": false
          },
          {
            "club": "Club Brugge",
            "from": 2019,
            "to": 2026,
            "apps": 223,
            "loan": false
          }
        ],
        "birthYear": 1988,
        "source": "https://en.wikipedia.org/wiki/Simon_Mignolet",
        "scramble": "GNIOETML",
        "fixed": 0,
        "len": [
          8
        ]
      },
      {
        "id": "s2",
        "band": "b1",
        "x": 0.2,
        "pos": "LB",
        "name": "ANTONEE ROBINSON",
        "display": "ANTONEE ROBINSON",
        "aliases": [],
        "club": null,
        "nationality": "United States",
        "clubs": [
          {
            "club": "Bolton Wanderers",
            "from": 2017,
            "to": 2018,
            "apps": 30,
            "loan": true
          },
          {
            "club": "Wigan Athletic",
            "from": 2018,
            "to": 2019,
            "apps": 26,
            "loan": true
          },
          {
            "club": "Wigan Athletic",
            "from": 2019,
            "to": 2020,
            "apps": 38,
            "loan": false
          },
          {
            "club": "Fulham",
            "from": 2020,
            "to": 2020,
            "apps": 196,
            "loan": false
          }
        ],
        "birthYear": 1997,
        "source": "https://en.wikipedia.org/wiki/Antonee_Robinson",
        "scramble": "NENETAONBONROSI",
        "fixed": 0,
        "len": [
          7,
          8
        ]
      },
      {
        "id": "s3",
        "band": "b1",
        "x": 0.4,
        "pos": "CB",
        "name": "NELSEN",
        "display": "RYAN NELSEN",
        "aliases": [
          "RYAN NELSEN"
        ],
        "club": null,
        "nationality": "New Zealand",
        "clubs": [
          {
            "club": "Christchurch United",
            "from": 1995,
            "to": 1998,
            "apps": 96,
            "loan": false
          },
          {
            "club": "D.C. United",
            "from": 2001,
            "to": 2005,
            "apps": 81,
            "loan": false
          },
          {
            "club": "Blackburn Rovers",
            "from": 2005,
            "to": 2012,
            "apps": 172,
            "loan": false
          },
          {
            "club": "Tottenham Hotspur",
            "from": 2012,
            "to": 2012,
            "apps": 5,
            "loan": false
          },
          {
            "club": "Queens Park Rangers",
            "from": 2012,
            "to": 2013,
            "apps": 21,
            "loan": false
          }
        ],
        "birthYear": 1977,
        "source": "https://en.wikipedia.org/wiki/Ryan_Nelsen",
        "scramble": "SLNENE",
        "fixed": 0,
        "len": [
          6
        ]
      },
      {
        "id": "s4",
        "band": "b1",
        "x": 0.6,
        "pos": "CB",
        "name": "DIAS",
        "display": "RUBEN DIAS",
        "aliases": [
          "RUBEN DIAS"
        ],
        "club": null,
        "nationality": "Portugal",
        "clubs": [
          {
            "club": "Benfica B",
            "from": 2015,
            "to": 2017,
            "apps": 55,
            "loan": false
          },
          {
            "club": "Benfica",
            "from": 2017,
            "to": 2020,
            "apps": 91,
            "loan": false
          },
          {
            "club": "Manchester City",
            "from": 2020,
            "to": 2020,
            "apps": 172,
            "loan": false
          }
        ],
        "birthYear": 1997,
        "source": "https://en.wikipedia.org/wiki/Rúben_Dias",
        "scramble": "IASD",
        "fixed": 0,
        "len": [
          4
        ]
      },
      {
        "id": "s5",
        "band": "b1",
        "x": 0.8,
        "pos": "RB",
        "name": "DIARRA",
        "display": "LASSANA DIARRA",
        "aliases": [
          "LASSANA DIARRA"
        ],
        "club": null,
        "nationality": "France",
        "clubs": [
          {
            "club": "Le Havre",
            "from": 2004,
            "to": 2005,
            "apps": 29,
            "loan": false
          },
          {
            "club": "Chelsea",
            "from": 2005,
            "to": 2007,
            "apps": 13,
            "loan": false
          },
          {
            "club": "Arsenal",
            "from": 2007,
            "to": 2008,
            "apps": 7,
            "loan": false
          },
          {
            "club": "Portsmouth",
            "from": 2008,
            "to": 2009,
            "apps": 24,
            "loan": false
          },
          {
            "club": "Real Madrid",
            "from": 2009,
            "to": 2012,
            "apps": 87,
            "loan": false
          },
          {
            "club": "Anzhi Makhachkala",
            "from": 2012,
            "to": 2013,
            "apps": 18,
            "loan": false
          },
          {
            "club": "Lokomotiv Moscow",
            "from": 2013,
            "to": 2014,
            "apps": 17,
            "loan": false
          },
          {
            "club": "Marseille",
            "from": 2015,
            "to": 2017,
            "apps": 37,
            "loan": false
          },
          {
            "club": "Al Jazira",
            "from": 2017,
            "to": 2017,
            "apps": 5,
            "loan": false
          },
          {
            "club": "Paris Saint-Germain",
            "from": 2018,
            "to": 2019,
            "apps": 13,
            "loan": false
          }
        ],
        "birthYear": 1985,
        "source": "https://en.wikipedia.org/wiki/Lassana_Diarra",
        "scramble": "ARRDAI",
        "fixed": 0,
        "len": [
          6
        ]
      },
      {
        "id": "s6",
        "band": "b2",
        "x": 0.2,
        "pos": "LW",
        "name": "SON HEUNG-MIN",
        "display": "SON HEUNG-MIN",
        "aliases": [],
        "club": null,
        "nationality": "South Korea",
        "clubs": [
          {
            "club": "Hamburger SV II",
            "from": 2010,
            "to": 2010,
            "apps": 6,
            "loan": false
          },
          {
            "club": "Hamburger SV",
            "from": 2010,
            "to": 2013,
            "apps": 73,
            "loan": false
          },
          {
            "club": "Bayer Leverkusen",
            "from": 2013,
            "to": 2015,
            "apps": 62,
            "loan": false
          },
          {
            "club": "Tottenham Hotspur",
            "from": 2015,
            "to": 2025,
            "apps": 333,
            "loan": false
          },
          {
            "club": "Los Angeles FC",
            "from": 2025,
            "to": 2025,
            "apps": 31,
            "loan": false
          }
        ],
        "birthYear": 1992,
        "source": "https://en.wikipedia.org/wiki/Son_Heung-min",
        "scramble": "NSONIGHNEMU",
        "fixed": 0,
        "len": [
          3,
          8
        ]
      },
      {
        "id": "s7",
        "band": "b2",
        "x": 0.4,
        "pos": "CM",
        "name": "ODEGAARD",
        "display": "MARTIN ODEGAARD",
        "aliases": [
          "MARTIN ODEGAARD"
        ],
        "club": null,
        "nationality": "Norway",
        "clubs": [
          {
            "club": "Strømsgodset 3",
            "from": 2013,
            "to": 2013,
            "apps": 11,
            "loan": false
          },
          {
            "club": "Strømsgodset 2",
            "from": 2013,
            "to": 2014,
            "apps": 5,
            "loan": false
          },
          {
            "club": "Strømsgodset",
            "from": 2014,
            "to": 2015,
            "apps": 23,
            "loan": false
          },
          {
            "club": "Real Madrid Castilla",
            "from": 2015,
            "to": 2017,
            "apps": 58,
            "loan": false
          },
          {
            "club": "Real Madrid",
            "from": 2015,
            "to": 2021,
            "apps": 8,
            "loan": false
          },
          {
            "club": "Heerenveen",
            "from": 2017,
            "to": 2018,
            "apps": 38,
            "loan": true
          },
          {
            "club": "Vitesse",
            "from": 2018,
            "to": 2019,
            "apps": 31,
            "loan": true
          },
          {
            "club": "Real Sociedad",
            "from": 2019,
            "to": 2020,
            "apps": 31,
            "loan": true
          },
          {
            "club": "Arsenal",
            "from": 2021,
            "to": 2021,
            "apps": 14,
            "loan": true
          },
          {
            "club": "Arsenal",
            "from": 2021,
            "to": 2021,
            "apps": 164,
            "loan": false
          }
        ],
        "birthYear": 1998,
        "source": "https://en.wikipedia.org/wiki/Martin_Ødegaard",
        "scramble": "ERDAGDOA",
        "fixed": 0,
        "len": [
          8
        ]
      },
      {
        "id": "s8",
        "band": "b2",
        "x": 0.6,
        "pos": "CM",
        "name": "CARRICO",
        "display": "DANIEL CARRICO",
        "aliases": [
          "DANIEL CARRICO"
        ],
        "club": null,
        "nationality": "Portugal",
        "clubs": [
          {
            "club": "Sporting CP",
            "from": 2007,
            "to": 2012,
            "apps": 91,
            "loan": false
          },
          {
            "club": "Olhanense",
            "from": 2007,
            "to": 2007,
            "apps": 8,
            "loan": true
          },
          {
            "club": "AEL Limassol",
            "from": 2008,
            "to": 2008,
            "apps": 14,
            "loan": true
          },
          {
            "club": "Reading",
            "from": 2013,
            "to": 2014,
            "apps": 3,
            "loan": false
          },
          {
            "club": "Sevilla",
            "from": 2013,
            "to": 2014,
            "apps": 22,
            "loan": true
          },
          {
            "club": "Sevilla",
            "from": 2014,
            "to": 2020,
            "apps": 89,
            "loan": false
          },
          {
            "club": "Wuhan Zall",
            "from": 2020,
            "to": 2021,
            "apps": 20,
            "loan": false
          },
          {
            "club": "Almería",
            "from": 2021,
            "to": 2022,
            "apps": 6,
            "loan": false
          }
        ],
        "birthYear": 1988,
        "source": "https://en.wikipedia.org/wiki/Daniel_Carriço",
        "scramble": "ARCICOR",
        "fixed": 0,
        "len": [
          7
        ]
      },
      {
        "id": "s9",
        "band": "b2",
        "x": 0.8,
        "pos": "RW",
        "name": "GERA",
        "display": "ZOLTAN GERA",
        "aliases": [
          "ZOLTAN GERA"
        ],
        "club": null,
        "nationality": "Hungary",
        "clubs": [
          {
            "club": "Harkány SE",
            "from": 1996,
            "to": 1997,
            "apps": null,
            "loan": false
          },
          {
            "club": "Pécs",
            "from": 1997,
            "to": 2000,
            "apps": 71,
            "loan": false
          },
          {
            "club": "Ferencváros",
            "from": 2000,
            "to": 2004,
            "apps": 115,
            "loan": false
          },
          {
            "club": "West Bromwich Albion",
            "from": 2004,
            "to": 2008,
            "apps": 135,
            "loan": false
          },
          {
            "club": "Fulham",
            "from": 2008,
            "to": 2011,
            "apps": 86,
            "loan": false
          },
          {
            "club": "West Bromwich Albion",
            "from": 2011,
            "to": 2014,
            "apps": 30,
            "loan": false
          },
          {
            "club": "Ferencváros",
            "from": 2014,
            "to": 2018,
            "apps": 89,
            "loan": false
          }
        ],
        "birthYear": 1979,
        "source": "https://en.wikipedia.org/wiki/Zoltán_Gera",
        "scramble": "RGAE",
        "fixed": 0,
        "len": [
          4
        ]
      },
      {
        "id": "s10",
        "band": "b3",
        "x": 0.3333,
        "pos": "ST",
        "name": "CROUCH",
        "display": "PETER CROUCH",
        "aliases": [
          "PETER CROUCH"
        ],
        "club": null,
        "nationality": "England",
        "clubs": [
          {
            "club": "Dulwich Hamlet",
            "from": 2000,
            "to": 2000,
            "apps": 6,
            "loan": true
          },
          {
            "club": "IFK Hässleholm",
            "from": 2000,
            "to": 2000,
            "apps": 8,
            "loan": true
          },
          {
            "club": "Queens Park Rangers",
            "from": 2000,
            "to": 2001,
            "apps": 42,
            "loan": false
          },
          {
            "club": "Portsmouth",
            "from": 2001,
            "to": 2002,
            "apps": 37,
            "loan": false
          },
          {
            "club": "Aston Villa",
            "from": 2002,
            "to": 2004,
            "apps": 37,
            "loan": false
          },
          {
            "club": "Norwich City",
            "from": 2003,
            "to": 2003,
            "apps": 15,
            "loan": true
          },
          {
            "club": "Southampton",
            "from": 2004,
            "to": 2005,
            "apps": 27,
            "loan": false
          },
          {
            "club": "Liverpool",
            "from": 2005,
            "to": 2008,
            "apps": 85,
            "loan": false
          },
          {
            "club": "Portsmouth",
            "from": 2008,
            "to": 2009,
            "apps": 38,
            "loan": false
          },
          {
            "club": "Tottenham Hotspur",
            "from": 2009,
            "to": 2011,
            "apps": 73,
            "loan": false
          },
          {
            "club": "Stoke City",
            "from": 2011,
            "to": 2019,
            "apps": 225,
            "loan": false
          },
          {
            "club": "Burnley",
            "from": 2019,
            "to": 2019,
            "apps": 6,
            "loan": false
          }
        ],
        "birthYear": 1981,
        "source": "https://en.wikipedia.org/wiki/Peter_Crouch",
        "scramble": "RUCHOC",
        "fixed": 0,
        "len": [
          6
        ]
      },
      {
        "id": "s11",
        "band": "b3",
        "x": 0.6667,
        "pos": "ST",
        "name": "VARDY",
        "display": "JAMIE VARDY",
        "aliases": [
          "JAMIE VARDY"
        ],
        "club": null,
        "nationality": "England",
        "clubs": [
          {
            "club": "Stocksbridge Park Steels",
            "from": 2006,
            "to": 2010,
            "apps": 88,
            "loan": false
          },
          {
            "club": "Halifax Town",
            "from": 2010,
            "to": 2011,
            "apps": 37,
            "loan": false
          },
          {
            "club": "Fleetwood Town",
            "from": 2011,
            "to": 2012,
            "apps": 36,
            "loan": false
          },
          {
            "club": "Leicester City",
            "from": 2012,
            "to": 2025,
            "apps": 440,
            "loan": false
          },
          {
            "club": "Cremonese",
            "from": 2025,
            "to": 2026,
            "apps": 29,
            "loan": false
          }
        ],
        "birthYear": 1987,
        "source": "https://en.wikipedia.org/wiki/Jamie_Vardy",
        "scramble": "RVDYA",
        "fixed": 0,
        "len": [
          5
        ]
      }
    ]
  },
  {
    "id": 2,
    "title": "Daily XI, 4-3-3",
    "pool": "Eleven Premier League players. Not a team — nobody here lined up together.",
    "formation": "4-3-3",
    "hintField": "clubs",
    "source": "generated from research/daily/daily-roster.json; every player sourced and verified individually",
    "bands": [
      {
        "id": "gk",
        "y": 0.9
      },
      {
        "id": "b1",
        "y": 0.74
      },
      {
        "id": "b2",
        "y": 0.45
      },
      {
        "id": "b3",
        "y": 0.16
      }
    ],
    "slots": [
      {
        "id": "s1",
        "band": "gk",
        "x": 0.5,
        "pos": "GK",
        "name": "CARSON",
        "display": "SCOTT CARSON",
        "aliases": [
          "SCOTT CARSON"
        ],
        "club": null,
        "nationality": "England",
        "clubs": [
          {
            "club": "Leeds United",
            "from": 2003,
            "to": 2005,
            "apps": 3,
            "loan": false
          },
          {
            "club": "Liverpool",
            "from": 2005,
            "to": 2008,
            "apps": 4,
            "loan": false
          },
          {
            "club": "Sheffield Wednesday",
            "from": 2006,
            "to": 2006,
            "apps": 9,
            "loan": true
          },
          {
            "club": "Charlton Athletic",
            "from": 2006,
            "to": 2007,
            "apps": 36,
            "loan": true
          },
          {
            "club": "Aston Villa",
            "from": 2007,
            "to": 2008,
            "apps": 35,
            "loan": true
          },
          {
            "club": "West Bromwich Albion",
            "from": 2008,
            "to": 2011,
            "apps": 110,
            "loan": false
          },
          {
            "club": "Bursaspor",
            "from": 2011,
            "to": 2013,
            "apps": 63,
            "loan": false
          },
          {
            "club": "Wigan Athletic",
            "from": 2013,
            "to": 2015,
            "apps": 50,
            "loan": false
          },
          {
            "club": "Derby County",
            "from": 2015,
            "to": 2021,
            "apps": 158,
            "loan": false
          },
          {
            "club": "Manchester City",
            "from": 2019,
            "to": 2021,
            "apps": 1,
            "loan": true
          }
        ],
        "birthYear": 1985,
        "source": "https://en.wikipedia.org/wiki/Scott_Carson",
        "scramble": "AOCNRS",
        "fixed": 0,
        "len": [
          6
        ]
      },
      {
        "id": "s2",
        "band": "b1",
        "x": 0.2,
        "pos": "LB",
        "name": "VALENTE",
        "display": "NUNO VALENTE",
        "aliases": [
          "NUNO VALENTE"
        ],
        "club": null,
        "nationality": "Portugal",
        "clubs": [
          {
            "club": "Sporting CP",
            "from": 1993,
            "to": 1999,
            "apps": 36,
            "loan": false
          },
          {
            "club": "Portimonense",
            "from": 1993,
            "to": 1994,
            "apps": 26,
            "loan": true
          },
          {
            "club": "Marítimo",
            "from": 1996,
            "to": 1997,
            "apps": 30,
            "loan": true
          },
          {
            "club": "União Leiria",
            "from": 1999,
            "to": 2002,
            "apps": 87,
            "loan": false
          },
          {
            "club": "Porto",
            "from": 2002,
            "to": 2005,
            "apps": 56,
            "loan": false
          },
          {
            "club": "Everton",
            "from": 2005,
            "to": 2009,
            "apps": 45,
            "loan": false
          }
        ],
        "birthYear": 1974,
        "source": "https://en.wikipedia.org/wiki/Nuno_Valente",
        "scramble": "LENAEVT",
        "fixed": 0,
        "len": [
          7
        ]
      },
      {
        "id": "s3",
        "band": "b1",
        "x": 0.4,
        "pos": "CB",
        "name": "RICHARDS",
        "display": "DEAN RICHARDS",
        "aliases": [
          "DEAN RICHARDS"
        ],
        "club": null,
        "nationality": "England",
        "clubs": [
          {
            "club": "Bradford City",
            "from": 1992,
            "to": 1995,
            "apps": 86,
            "loan": false
          },
          {
            "club": "Wolverhampton Wanderers",
            "from": 1995,
            "to": 1995,
            "apps": 10,
            "loan": true
          },
          {
            "club": "Wolverhampton Wanderers",
            "from": 1995,
            "to": 1999,
            "apps": 112,
            "loan": false
          },
          {
            "club": "Southampton",
            "from": 1999,
            "to": 2001,
            "apps": 67,
            "loan": false
          },
          {
            "club": "Tottenham Hotspur",
            "from": 2001,
            "to": 2005,
            "apps": 73,
            "loan": false
          }
        ],
        "birthYear": 1974,
        "source": "https://en.wikipedia.org/wiki/Dean_Richards_(footballer)",
        "scramble": "DSHICARR",
        "fixed": 0,
        "len": [
          8
        ]
      },
      {
        "id": "s4",
        "band": "b1",
        "x": 0.6,
        "pos": "CB",
        "name": "PINNOCK",
        "display": "ETHAN PINNOCK",
        "aliases": [
          "ETHAN PINNOCK"
        ],
        "club": null,
        "nationality": "Jamaica",
        "clubs": [
          {
            "club": "Dulwich Hamlet",
            "from": 2010,
            "to": 2016,
            "apps": 159,
            "loan": false
          },
          {
            "club": "Holmesdale",
            "from": 2011,
            "to": 2011,
            "apps": null,
            "loan": true
          },
          {
            "club": "Forest Green Rovers",
            "from": 2016,
            "to": 2017,
            "apps": 37,
            "loan": false
          },
          {
            "club": "Barnsley",
            "from": 2017,
            "to": 2019,
            "apps": 58,
            "loan": false
          },
          {
            "club": "Brentford",
            "from": 2019,
            "to": 2026,
            "apps": 192,
            "loan": false
          },
          {
            "club": "Coventry City",
            "from": 2026,
            "to": 2026,
            "apps": 1,
            "loan": false
          }
        ],
        "birthYear": 1993,
        "source": "https://en.wikipedia.org/wiki/Ethan_Pinnock",
        "scramble": "INCKPON",
        "fixed": 0,
        "len": [
          7
        ]
      },
      {
        "id": "s5",
        "band": "b1",
        "x": 0.8,
        "pos": "RB",
        "name": "BOSINGWA",
        "display": "JOSE BOSINGWA",
        "aliases": [
          "JOSE BOSINGWA"
        ],
        "club": null,
        "nationality": "Portugal",
        "clubs": [
          {
            "club": "Boavista",
            "from": 2000,
            "to": 2003,
            "apps": 41,
            "loan": false
          },
          {
            "club": "Freamunde",
            "from": 2000,
            "to": 2001,
            "apps": 11,
            "loan": true
          },
          {
            "club": "Porto",
            "from": 2003,
            "to": 2008,
            "apps": 107,
            "loan": false
          },
          {
            "club": "Chelsea",
            "from": 2008,
            "to": 2012,
            "apps": 89,
            "loan": false
          },
          {
            "club": "Queens Park Rangers",
            "from": 2012,
            "to": 2013,
            "apps": 23,
            "loan": false
          },
          {
            "club": "Trabzonspor",
            "from": 2013,
            "to": 2015,
            "apps": 51,
            "loan": false
          },
          {
            "club": "Trabzonspor",
            "from": 2016,
            "to": 2016,
            "apps": 12,
            "loan": false
          }
        ],
        "birthYear": 1982,
        "source": "https://en.wikipedia.org/wiki/José_Bosingwa",
        "scramble": "IWNAGOBS",
        "fixed": 0,
        "len": [
          8
        ]
      },
      {
        "id": "s6",
        "band": "b2",
        "x": 0.25,
        "pos": "CM",
        "name": "O'NEIL",
        "display": "GARY O'NEIL",
        "aliases": [
          "GARY O'NEIL"
        ],
        "club": null,
        "nationality": "England",
        "clubs": [
          {
            "club": "Portsmouth",
            "from": 2000,
            "to": 2007,
            "apps": 174,
            "loan": false
          },
          {
            "club": "Walsall",
            "from": 2003,
            "to": 2003,
            "apps": 7,
            "loan": true
          },
          {
            "club": "Cardiff City",
            "from": 2004,
            "to": 2004,
            "apps": 9,
            "loan": true
          },
          {
            "club": "Middlesbrough",
            "from": 2007,
            "to": 2011,
            "apps": 109,
            "loan": false
          },
          {
            "club": "West Ham United",
            "from": 2011,
            "to": 2013,
            "apps": 48,
            "loan": false
          },
          {
            "club": "Queens Park Rangers",
            "from": 2013,
            "to": 2014,
            "apps": 29,
            "loan": false
          },
          {
            "club": "Norwich City",
            "from": 2014,
            "to": 2016,
            "apps": 51,
            "loan": false
          },
          {
            "club": "Bristol City",
            "from": 2016,
            "to": 2018,
            "apps": 33,
            "loan": false
          },
          {
            "club": "Bolton Wanderers",
            "from": 2018,
            "to": 2019,
            "apps": 29,
            "loan": false
          }
        ],
        "birthYear": 1983,
        "source": "https://en.wikipedia.org/wiki/Gary_O'Neil",
        "scramble": "IEOLN",
        "fixed": 0,
        "len": [
          5
        ]
      },
      {
        "id": "s7",
        "band": "b2",
        "x": 0.5,
        "pos": "CM",
        "name": "LUIZ",
        "display": "DOUGLAS LUIZ",
        "aliases": [
          "DOUGLAS LUIZ"
        ],
        "club": null,
        "nationality": "Brazil",
        "clubs": [
          {
            "club": "Vasco da Gama",
            "from": 2016,
            "to": 2017,
            "apps": 35,
            "loan": false
          },
          {
            "club": "Girona",
            "from": 2017,
            "to": 2019,
            "apps": 38,
            "loan": true
          },
          {
            "club": "Aston Villa",
            "from": 2019,
            "to": 2024,
            "apps": 175,
            "loan": false
          },
          {
            "club": "Juventus",
            "from": 2024,
            "to": 2024,
            "apps": 21,
            "loan": false
          },
          {
            "club": "Nottingham Forest",
            "from": 2025,
            "to": 2026,
            "apps": 8,
            "loan": true
          },
          {
            "club": "Aston Villa",
            "from": 2026,
            "to": 2026,
            "apps": 13,
            "loan": true
          }
        ],
        "birthYear": 1998,
        "source": "https://en.wikipedia.org/wiki/Douglas_Luiz",
        "scramble": "IZUL",
        "fixed": 0,
        "len": [
          4
        ]
      },
      {
        "id": "s8",
        "band": "b2",
        "x": 0.75,
        "pos": "CM",
        "name": "MENDIETA",
        "display": "GAIZKA MENDIETA",
        "aliases": [
          "GAIZKA MENDIETA"
        ],
        "club": null,
        "nationality": "Spain",
        "clubs": [
          {
            "club": "Castellón",
            "from": 1992,
            "to": 1992,
            "apps": 16,
            "loan": false
          },
          {
            "club": "Valencia B",
            "from": 1992,
            "to": 1994,
            "apps": 34,
            "loan": false
          },
          {
            "club": "Valencia",
            "from": 1993,
            "to": 2001,
            "apps": 230,
            "loan": false
          },
          {
            "club": "Lazio",
            "from": 2001,
            "to": 2004,
            "apps": 20,
            "loan": false
          },
          {
            "club": "Barcelona",
            "from": 2002,
            "to": 2003,
            "apps": 33,
            "loan": true
          },
          {
            "club": "Middlesbrough",
            "from": 2003,
            "to": 2004,
            "apps": 31,
            "loan": true
          },
          {
            "club": "Middlesbrough",
            "from": 2004,
            "to": 2008,
            "apps": 31,
            "loan": false
          }
        ],
        "birthYear": 1974,
        "source": "https://en.wikipedia.org/wiki/Gaizka_Mendieta",
        "scramble": "DMINATEE",
        "fixed": 0,
        "len": [
          8
        ]
      },
      {
        "id": "s9",
        "band": "b3",
        "x": 0.25,
        "pos": "LW",
        "name": "PARK",
        "display": "PARK JI-SUNG",
        "aliases": [
          "PARK JI-SUNG"
        ],
        "club": null,
        "nationality": "South Korea",
        "clubs": [
          {
            "club": "Kyoto Purple Sanga",
            "from": 2000,
            "to": 2003,
            "apps": 76,
            "loan": false
          },
          {
            "club": "PSV Eindhoven",
            "from": 2003,
            "to": 2005,
            "apps": 65,
            "loan": false
          },
          {
            "club": "Manchester United",
            "from": 2005,
            "to": 2012,
            "apps": 134,
            "loan": false
          },
          {
            "club": "Queens Park Rangers",
            "from": 2012,
            "to": 2014,
            "apps": 20,
            "loan": false
          },
          {
            "club": "PSV Eindhoven",
            "from": 2013,
            "to": 2014,
            "apps": 23,
            "loan": true
          }
        ],
        "birthYear": 1981,
        "source": "https://en.wikipedia.org/wiki/Park_Ji-sung",
        "scramble": "KRPA",
        "fixed": 0,
        "len": [
          4
        ]
      },
      {
        "id": "s10",
        "band": "b3",
        "x": 0.5,
        "pos": "ST",
        "name": "RASHFORD",
        "display": "MARCUS RASHFORD",
        "aliases": [
          "MARCUS RASHFORD"
        ],
        "club": null,
        "nationality": "England",
        "clubs": [
          {
            "club": "Manchester United",
            "from": 2015,
            "to": 2015,
            "apps": 289,
            "loan": false
          },
          {
            "club": "Aston Villa",
            "from": 2025,
            "to": 2025,
            "apps": 10,
            "loan": true
          },
          {
            "club": "Barcelona",
            "from": 2025,
            "to": 2026,
            "apps": 32,
            "loan": true
          }
        ],
        "birthYear": 1997,
        "source": "https://en.wikipedia.org/wiki/Marcus_Rashford",
        "scramble": "DRORHSAF",
        "fixed": 0,
        "len": [
          8
        ]
      },
      {
        "id": "s11",
        "band": "b3",
        "x": 0.75,
        "pos": "RW",
        "name": "MAHREZ",
        "display": "RIYAD MAHREZ",
        "aliases": [
          "RIYAD MAHREZ"
        ],
        "club": null,
        "nationality": "Algeria",
        "clubs": [
          {
            "club": "Quimper",
            "from": 2009,
            "to": 2010,
            "apps": 27,
            "loan": false
          },
          {
            "club": "Le Havre II",
            "from": 2010,
            "to": 2013,
            "apps": 60,
            "loan": false
          },
          {
            "club": "Le Havre",
            "from": 2011,
            "to": 2014,
            "apps": 60,
            "loan": false
          },
          {
            "club": "Leicester City",
            "from": 2014,
            "to": 2018,
            "apps": 158,
            "loan": false
          },
          {
            "club": "Manchester City",
            "from": 2018,
            "to": 2023,
            "apps": 145,
            "loan": false
          },
          {
            "club": "Al-Ahli",
            "from": 2023,
            "to": 2026,
            "apps": 90,
            "loan": false
          }
        ],
        "birthYear": 1991,
        "source": "https://en.wikipedia.org/wiki/Riyad_Mahrez",
        "scramble": "EMRHZA",
        "fixed": 0,
        "len": [
          6
        ]
      }
    ]
  },
  {
    "id": 3,
    "title": "Daily XI, 4-4-2",
    "pool": "Eleven Premier League players. Not a team — nobody here lined up together.",
    "formation": "4-4-2",
    "hintField": "clubs",
    "source": "generated from research/daily/daily-roster.json; every player sourced and verified individually",
    "bands": [
      {
        "id": "gk",
        "y": 0.9
      },
      {
        "id": "b1",
        "y": 0.74
      },
      {
        "id": "b2",
        "y": 0.45
      },
      {
        "id": "b3",
        "y": 0.16
      }
    ],
    "slots": [
      {
        "id": "s1",
        "band": "gk",
        "x": 0.5,
        "pos": "GK",
        "name": "KELLER",
        "display": "KASEY KELLER",
        "aliases": [
          "KASEY KELLER"
        ],
        "club": null,
        "nationality": "United States",
        "clubs": [
          {
            "club": "Portland Timbers",
            "from": 1989,
            "to": 1989,
            "apps": 10,
            "loan": false
          },
          {
            "club": "Millwall",
            "from": 1992,
            "to": 1996,
            "apps": 175,
            "loan": false
          },
          {
            "club": "Leicester City",
            "from": 1996,
            "to": 1999,
            "apps": 99,
            "loan": false
          },
          {
            "club": "Rayo Vallecano",
            "from": 1999,
            "to": 2001,
            "apps": 51,
            "loan": false
          },
          {
            "club": "Tottenham Hotspur",
            "from": 2001,
            "to": 2005,
            "apps": 85,
            "loan": false
          },
          {
            "club": "Southampton",
            "from": 2004,
            "to": 2004,
            "apps": 4,
            "loan": true
          },
          {
            "club": "Borussia Mönchengladbach",
            "from": 2005,
            "to": 2007,
            "apps": 78,
            "loan": false
          },
          {
            "club": "Fulham",
            "from": 2007,
            "to": 2008,
            "apps": 13,
            "loan": false
          },
          {
            "club": "Seattle Sounders FC",
            "from": 2009,
            "to": 2011,
            "apps": 93,
            "loan": false
          }
        ],
        "birthYear": 1969,
        "source": "https://en.wikipedia.org/wiki/Kasey_Keller",
        "scramble": "EREKLL",
        "fixed": 0,
        "len": [
          6
        ]
      },
      {
        "id": "s2",
        "band": "b1",
        "x": 0.2,
        "pos": "LB",
        "name": "DORIGO",
        "display": "TONY DORIGO",
        "aliases": [
          "TONY DORIGO"
        ],
        "club": null,
        "nationality": "England",
        "clubs": [
          {
            "club": "Aston Villa",
            "from": 1984,
            "to": 1987,
            "apps": 111,
            "loan": false
          },
          {
            "club": "Chelsea",
            "from": 1987,
            "to": 1991,
            "apps": 146,
            "loan": false
          },
          {
            "club": "Leeds United",
            "from": 1991,
            "to": 1997,
            "apps": 171,
            "loan": false
          },
          {
            "club": "Torino",
            "from": 1997,
            "to": 1998,
            "apps": 30,
            "loan": false
          },
          {
            "club": "Derby County",
            "from": 1998,
            "to": 2000,
            "apps": 41,
            "loan": false
          },
          {
            "club": "Stoke City",
            "from": 2000,
            "to": 2001,
            "apps": 36,
            "loan": false
          }
        ],
        "birthYear": 1965,
        "source": "https://en.wikipedia.org/wiki/Tony_Dorigo",
        "scramble": "OGODRI",
        "fixed": 0,
        "len": [
          6
        ]
      },
      {
        "id": "s3",
        "band": "b1",
        "x": 0.4,
        "pos": "CB",
        "name": "MEE",
        "display": "BEN MEE",
        "aliases": [
          "BEN MEE"
        ],
        "club": null,
        "nationality": "England",
        "clubs": [
          {
            "club": "Leicester City",
            "from": 2011,
            "to": 2011,
            "apps": 15,
            "loan": true
          },
          {
            "club": "Burnley",
            "from": 2011,
            "to": 2012,
            "apps": 19,
            "loan": true
          },
          {
            "club": "Burnley",
            "from": 2012,
            "to": 2022,
            "apps": 332,
            "loan": false
          },
          {
            "club": "Brentford",
            "from": 2022,
            "to": 2025,
            "apps": 60,
            "loan": false
          },
          {
            "club": "Sheffield United",
            "from": 2025,
            "to": 2026,
            "apps": 15,
            "loan": false
          }
        ],
        "birthYear": 1989,
        "source": "https://en.wikipedia.org/wiki/Ben_Mee",
        "scramble": "EEM",
        "fixed": 1,
        "len": [
          3
        ]
      },
      {
        "id": "s4",
        "band": "b1",
        "x": 0.6,
        "pos": "CB",
        "name": "PETIT",
        "display": "EMMANUEL PETIT",
        "aliases": [
          "EMMANUEL PETIT"
        ],
        "club": null,
        "nationality": "France",
        "clubs": [
          {
            "club": "Monaco",
            "from": 1988,
            "to": 1997,
            "apps": 222,
            "loan": false
          },
          {
            "club": "Arsenal",
            "from": 1997,
            "to": 2000,
            "apps": 85,
            "loan": false
          },
          {
            "club": "Barcelona",
            "from": 2000,
            "to": 2001,
            "apps": 23,
            "loan": false
          },
          {
            "club": "Chelsea",
            "from": 2001,
            "to": 2004,
            "apps": 55,
            "loan": false
          }
        ],
        "birthYear": 1970,
        "source": "https://en.wikipedia.org/wiki/Emmanuel_Petit",
        "scramble": "TTIEP",
        "fixed": 0,
        "len": [
          5
        ]
      },
      {
        "id": "s5",
        "band": "b1",
        "x": 0.8,
        "pos": "RB",
        "name": "COX",
        "display": "NEIL COX",
        "aliases": [
          "NEIL COX"
        ],
        "club": null,
        "nationality": "England",
        "clubs": [
          {
            "club": "Scunthorpe United",
            "from": 1990,
            "to": 1991,
            "apps": 17,
            "loan": false
          },
          {
            "club": "Aston Villa",
            "from": 1991,
            "to": 1994,
            "apps": 40,
            "loan": false
          },
          {
            "club": "Middlesbrough",
            "from": 1994,
            "to": 1997,
            "apps": 106,
            "loan": false
          },
          {
            "club": "Bolton Wanderers",
            "from": 1997,
            "to": 1999,
            "apps": 80,
            "loan": false
          },
          {
            "club": "Watford",
            "from": 1999,
            "to": 2005,
            "apps": 219,
            "loan": false
          },
          {
            "club": "Cardiff City",
            "from": 2005,
            "to": 2006,
            "apps": 27,
            "loan": false
          },
          {
            "club": "Crewe Alexandra",
            "from": 2006,
            "to": 2008,
            "apps": 58,
            "loan": false
          },
          {
            "club": "Leek Town",
            "from": 2010,
            "to": 2011,
            "apps": 4,
            "loan": false
          }
        ],
        "birthYear": 1971,
        "source": "https://en.wikipedia.org/wiki/Neil_Cox_(footballer)",
        "scramble": "XCO",
        "fixed": 0,
        "len": [
          3
        ]
      },
      {
        "id": "s6",
        "band": "b2",
        "x": 0.2,
        "pos": "LW",
        "name": "BENRAHMA",
        "display": "SAID BENRAHMA",
        "aliases": [
          "SAID BENRAHMA"
        ],
        "club": null,
        "nationality": "Algeria",
        "clubs": [
          {
            "club": "Nice II",
            "from": 2013,
            "to": 2016,
            "apps": 37,
            "loan": false
          },
          {
            "club": "Nice",
            "from": 2013,
            "to": 2018,
            "apps": 17,
            "loan": false
          },
          {
            "club": "Angers",
            "from": 2016,
            "to": 2016,
            "apps": 12,
            "loan": true
          },
          {
            "club": "Angers II",
            "from": 2016,
            "to": 2016,
            "apps": 3,
            "loan": true
          },
          {
            "club": "Gazélec",
            "from": 2017,
            "to": 2017,
            "apps": 15,
            "loan": true
          },
          {
            "club": "Châteauroux",
            "from": 2017,
            "to": 2018,
            "apps": 31,
            "loan": true
          },
          {
            "club": "Brentford",
            "from": 2018,
            "to": 2021,
            "apps": 83,
            "loan": false
          },
          {
            "club": "West Ham United",
            "from": 2020,
            "to": 2021,
            "apps": 30,
            "loan": true
          },
          {
            "club": "West Ham United",
            "from": 2021,
            "to": 2024,
            "apps": 80,
            "loan": false
          },
          {
            "club": "Lyon",
            "from": 2024,
            "to": 2024,
            "apps": 12,
            "loan": true
          },
          {
            "club": "Lyon",
            "from": 2024,
            "to": 2025,
            "apps": 13,
            "loan": false
          },
          {
            "club": "Neom",
            "from": 2025,
            "to": 2025,
            "apps": 16,
            "loan": true
          },
          {
            "club": "Neom",
            "from": 2025,
            "to": 2025,
            "apps": 29,
            "loan": false
          }
        ],
        "birthYear": 1995,
        "source": "https://en.wikipedia.org/wiki/Saïd_Benrahma",
        "scramble": "HBANMRAE",
        "fixed": 0,
        "len": [
          8
        ]
      },
      {
        "id": "s7",
        "band": "b2",
        "x": 0.4,
        "pos": "CM",
        "name": "ARTER",
        "display": "HARRY ARTER",
        "aliases": [
          "HARRY ARTER"
        ],
        "club": null,
        "nationality": "Republic of Ireland",
        "clubs": [
          {
            "club": "Staines Town",
            "from": 2008,
            "to": 2008,
            "apps": 4,
            "loan": true
          },
          {
            "club": "Welling United",
            "from": 2009,
            "to": 2009,
            "apps": 6,
            "loan": true
          },
          {
            "club": "Woking",
            "from": 2009,
            "to": 2010,
            "apps": 36,
            "loan": false
          },
          {
            "club": "Bournemouth",
            "from": 2010,
            "to": 2020,
            "apps": 232,
            "loan": false
          },
          {
            "club": "Carlisle United",
            "from": 2011,
            "to": 2011,
            "apps": 5,
            "loan": true
          },
          {
            "club": "Cardiff City",
            "from": 2018,
            "to": 2019,
            "apps": 25,
            "loan": true
          },
          {
            "club": "Fulham",
            "from": 2019,
            "to": 2020,
            "apps": 28,
            "loan": true
          },
          {
            "club": "Nottingham Forest",
            "from": 2020,
            "to": 2024,
            "apps": 13,
            "loan": false
          },
          {
            "club": "Charlton Athletic",
            "from": 2021,
            "to": 2022,
            "apps": 4,
            "loan": true
          },
          {
            "club": "Notts County",
            "from": 2022,
            "to": 2022,
            "apps": 9,
            "loan": true
          },
          {
            "club": "Precision",
            "from": 2024,
            "to": 2025,
            "apps": 6,
            "loan": false
          }
        ],
        "birthYear": 1989,
        "source": "https://en.wikipedia.org/wiki/Harry_Arter",
        "scramble": "RTERA",
        "fixed": 0,
        "len": [
          5
        ]
      },
      {
        "id": "s8",
        "band": "b2",
        "x": 0.6,
        "pos": "CM",
        "name": "JONES",
        "display": "DAVID JONES",
        "aliases": [
          "DAVID JONES"
        ],
        "club": null,
        "nationality": "England",
        "clubs": [
          {
            "club": "Preston North End",
            "from": 2005,
            "to": 2006,
            "apps": 24,
            "loan": true
          },
          {
            "club": "NEC",
            "from": 2006,
            "to": 2006,
            "apps": 17,
            "loan": true
          },
          {
            "club": "Derby County",
            "from": 2006,
            "to": 2007,
            "apps": 10,
            "loan": true
          },
          {
            "club": "Derby County",
            "from": 2007,
            "to": 2008,
            "apps": 32,
            "loan": false
          },
          {
            "club": "Wolverhampton Wanderers",
            "from": 2008,
            "to": 2011,
            "apps": 66,
            "loan": false
          },
          {
            "club": "Wigan Athletic",
            "from": 2011,
            "to": 2013,
            "apps": 29,
            "loan": false
          },
          {
            "club": "Blackburn Rovers",
            "from": 2013,
            "to": 2013,
            "apps": 12,
            "loan": true
          },
          {
            "club": "Burnley",
            "from": 2013,
            "to": 2016,
            "apps": 124,
            "loan": false
          },
          {
            "club": "Sheffield Wednesday",
            "from": 2016,
            "to": 2019,
            "apps": 57,
            "loan": false
          },
          {
            "club": "Oldham Athletic",
            "from": 2019,
            "to": 2020,
            "apps": 6,
            "loan": false
          },
          {
            "club": "Wrexham",
            "from": 2021,
            "to": 2022,
            "apps": 4,
            "loan": false
          }
        ],
        "birthYear": 1984,
        "source": "https://en.wikipedia.org/wiki/David_Jones_(footballer,_born_1984)",
        "scramble": "NSOJE",
        "fixed": 0,
        "len": [
          5
        ]
      },
      {
        "id": "s9",
        "band": "b2",
        "x": 0.8,
        "pos": "RW",
        "name": "SOLSKJAER",
        "display": "OLE GUNNAR SOLSKJAER",
        "aliases": [
          "OLE GUNNAR SOLSKJAER"
        ],
        "club": null,
        "nationality": "Norway",
        "clubs": [
          {
            "club": "Clausenengen",
            "from": 1990,
            "to": 1995,
            "apps": 109,
            "loan": false
          },
          {
            "club": "Molde",
            "from": 1995,
            "to": 1996,
            "apps": 42,
            "loan": false
          },
          {
            "club": "Manchester United",
            "from": 1996,
            "to": 2007,
            "apps": 235,
            "loan": false
          }
        ],
        "birthYear": 1973,
        "source": "https://en.wikipedia.org/wiki/Ole_Gunnar_Solskjær",
        "scramble": "JSRESALOK",
        "fixed": 0,
        "len": [
          9
        ]
      },
      {
        "id": "s10",
        "band": "b3",
        "x": 0.3333,
        "pos": "ST",
        "name": "STURRIDGE",
        "display": "DANIEL STURRIDGE",
        "aliases": [
          "DANIEL STURRIDGE"
        ],
        "club": null,
        "nationality": "England",
        "clubs": [
          {
            "club": "Manchester City",
            "from": 2006,
            "to": 2009,
            "apps": 21,
            "loan": false
          },
          {
            "club": "Chelsea",
            "from": 2009,
            "to": 2013,
            "apps": 63,
            "loan": false
          },
          {
            "club": "Bolton Wanderers",
            "from": 2011,
            "to": 2011,
            "apps": 12,
            "loan": true
          },
          {
            "club": "Liverpool",
            "from": 2013,
            "to": 2019,
            "apps": 116,
            "loan": false
          },
          {
            "club": "West Bromwich Albion",
            "from": 2018,
            "to": 2018,
            "apps": 6,
            "loan": true
          },
          {
            "club": "Trabzonspor",
            "from": 2019,
            "to": 2020,
            "apps": 11,
            "loan": false
          },
          {
            "club": "Perth Glory",
            "from": 2021,
            "to": 2022,
            "apps": 6,
            "loan": false
          }
        ],
        "birthYear": 1989,
        "source": "https://en.wikipedia.org/wiki/Daniel_Sturridge",
        "scramble": "RGIEUDRST",
        "fixed": 0,
        "len": [
          9
        ]
      },
      {
        "id": "s11",
        "band": "b3",
        "x": 0.6667,
        "pos": "ST",
        "name": "WALTERS",
        "display": "JONATHAN WALTERS",
        "aliases": [
          "JONATHAN WALTERS"
        ],
        "club": null,
        "nationality": "Republic of Ireland",
        "clubs": [
          {
            "club": "Bolton Wanderers",
            "from": 2001,
            "to": 2004,
            "apps": 4,
            "loan": false
          },
          {
            "club": "Hull City",
            "from": 2003,
            "to": 2003,
            "apps": 11,
            "loan": true
          },
          {
            "club": "Barnsley",
            "from": 2003,
            "to": 2004,
            "apps": 8,
            "loan": true
          },
          {
            "club": "Hull City",
            "from": 2004,
            "to": 2005,
            "apps": 37,
            "loan": false
          },
          {
            "club": "Scunthorpe United",
            "from": 2005,
            "to": 2005,
            "apps": 3,
            "loan": true
          },
          {
            "club": "Wrexham",
            "from": 2005,
            "to": 2006,
            "apps": 38,
            "loan": false
          },
          {
            "club": "Chester City",
            "from": 2006,
            "to": 2007,
            "apps": 26,
            "loan": false
          },
          {
            "club": "Ipswich Town",
            "from": 2007,
            "to": 2010,
            "apps": 136,
            "loan": false
          },
          {
            "club": "Stoke City",
            "from": 2010,
            "to": 2017,
            "apps": 226,
            "loan": false
          },
          {
            "club": "Burnley",
            "from": 2017,
            "to": 2019,
            "apps": 3,
            "loan": false
          },
          {
            "club": "Ipswich Town",
            "from": 2018,
            "to": 2018,
            "apps": 3,
            "loan": true
          }
        ],
        "birthYear": 1983,
        "source": "https://en.wikipedia.org/wiki/Jonathan_Walters",
        "scramble": "ESRWALT",
        "fixed": 0,
        "len": [
          7
        ]
      }
    ]
  },
  {
    "id": 4,
    "title": "Daily XI, 4-3-3",
    "pool": "Eleven Premier League players. Not a team — nobody here lined up together.",
    "formation": "4-3-3",
    "hintField": "clubs",
    "source": "generated from research/daily/daily-roster.json; every player sourced and verified individually",
    "bands": [
      {
        "id": "gk",
        "y": 0.9
      },
      {
        "id": "b1",
        "y": 0.74
      },
      {
        "id": "b2",
        "y": 0.45
      },
      {
        "id": "b3",
        "y": 0.16
      }
    ],
    "slots": [
      {
        "id": "s1",
        "band": "gk",
        "x": 0.5,
        "pos": "GK",
        "name": "GERRARD",
        "display": "PAUL GERRARD",
        "aliases": [
          "PAUL GERRARD"
        ],
        "club": null,
        "nationality": "England",
        "clubs": [
          {
            "club": "Oldham Athletic",
            "from": 1991,
            "to": 1996,
            "apps": 119,
            "loan": false
          },
          {
            "club": "Everton",
            "from": 1996,
            "to": 2004,
            "apps": 90,
            "loan": false
          },
          {
            "club": "Oxford United",
            "from": 1998,
            "to": 1999,
            "apps": 16,
            "loan": true
          },
          {
            "club": "Ipswich Town",
            "from": 2002,
            "to": 2002,
            "apps": 5,
            "loan": true
          },
          {
            "club": "Sheffield United",
            "from": 2003,
            "to": 2003,
            "apps": 16,
            "loan": true
          },
          {
            "club": "Nottingham Forest",
            "from": 2004,
            "to": 2004,
            "apps": 8,
            "loan": true
          },
          {
            "club": "Nottingham Forest",
            "from": 2004,
            "to": 2006,
            "apps": 64,
            "loan": false
          },
          {
            "club": "Sheffield United",
            "from": 2006,
            "to": 2008,
            "apps": 2,
            "loan": false
          },
          {
            "club": "Oldham Athletic",
            "from": 2010,
            "to": 2013,
            "apps": 1,
            "loan": false
          }
        ],
        "birthYear": 1973,
        "source": "https://en.wikipedia.org/wiki/Paul_Gerrard",
        "scramble": "RAGDRER",
        "fixed": 0,
        "len": [
          7
        ]
      },
      {
        "id": "s2",
        "band": "b1",
        "x": 0.2,
        "pos": "LB",
        "name": "BJORNEBYE",
        "display": "STIG INGE BJORNEBYE",
        "aliases": [
          "STIG INGE BJORNEBYE"
        ],
        "club": null,
        "nationality": "Norway",
        "clubs": [
          {
            "club": "Strømmen",
            "from": 1987,
            "to": 1988,
            "apps": 19,
            "loan": false
          },
          {
            "club": "Kongsvinger",
            "from": 1989,
            "to": 1992,
            "apps": 62,
            "loan": false
          },
          {
            "club": "Rosenborg",
            "from": 1992,
            "to": 1992,
            "apps": 21,
            "loan": false
          },
          {
            "club": "Liverpool",
            "from": 1992,
            "to": 2000,
            "apps": 139,
            "loan": false
          },
          {
            "club": "Rosenborg",
            "from": 1994,
            "to": 1994,
            "apps": 8,
            "loan": true
          },
          {
            "club": "Brøndby",
            "from": 2000,
            "to": 2000,
            "apps": 13,
            "loan": true
          },
          {
            "club": "Blackburn Rovers",
            "from": 2000,
            "to": 2003,
            "apps": 55,
            "loan": false
          }
        ],
        "birthYear": 1969,
        "source": "https://en.wikipedia.org/wiki/Stig_Inge_Bjørnebye",
        "scramble": "OENYRBEBJ",
        "fixed": 0,
        "len": [
          9
        ]
      },
      {
        "id": "s3",
        "band": "b1",
        "x": 0.4,
        "pos": "CB",
        "name": "HALL",
        "display": "MARCUS HALL",
        "aliases": [
          "MARCUS HALL"
        ],
        "club": null,
        "nationality": "England",
        "clubs": [
          {
            "club": "Coventry City",
            "from": 1994,
            "to": 2002,
            "apps": 132,
            "loan": false
          },
          {
            "club": "Nottingham Forest",
            "from": 2002,
            "to": 2002,
            "apps": 1,
            "loan": false
          },
          {
            "club": "Stoke City",
            "from": 2002,
            "to": 2005,
            "apps": 78,
            "loan": false
          },
          {
            "club": "Coventry City",
            "from": 2005,
            "to": 2010,
            "apps": 138,
            "loan": false
          },
          {
            "club": "Northampton Town",
            "from": 2010,
            "to": 2011,
            "apps": 24,
            "loan": false
          }
        ],
        "birthYear": 1976,
        "source": "https://en.wikipedia.org/wiki/Marcus_Hall",
        "scramble": "LLAH",
        "fixed": 0,
        "len": [
          4
        ]
      },
      {
        "id": "s4",
        "band": "b1",
        "x": 0.6,
        "pos": "CB",
        "name": "MELVILLE",
        "display": "ANDY MELVILLE",
        "aliases": [
          "ANDY MELVILLE"
        ],
        "club": null,
        "nationality": "Wales",
        "clubs": [
          {
            "club": "Swansea City",
            "from": 1986,
            "to": 1990,
            "apps": 175,
            "loan": false
          },
          {
            "club": "Oxford United",
            "from": 1990,
            "to": 1993,
            "apps": 135,
            "loan": false
          },
          {
            "club": "Sunderland",
            "from": 1993,
            "to": 1999,
            "apps": 204,
            "loan": false
          },
          {
            "club": "Bradford",
            "from": 1998,
            "to": 1998,
            "apps": 6,
            "loan": true
          },
          {
            "club": "Fulham",
            "from": 1999,
            "to": 2004,
            "apps": 153,
            "loan": false
          },
          {
            "club": "West Ham United",
            "from": 2004,
            "to": 2005,
            "apps": 17,
            "loan": false
          },
          {
            "club": "Nottingham Forest",
            "from": 2005,
            "to": 2005,
            "apps": 13,
            "loan": true
          }
        ],
        "birthYear": 1968,
        "source": "https://en.wikipedia.org/wiki/Andy_Melville",
        "scramble": "ELILEMVL",
        "fixed": 0,
        "len": [
          8
        ]
      },
      {
        "id": "s5",
        "band": "b1",
        "x": 0.8,
        "pos": "RB",
        "name": "FINNAN",
        "display": "STEVE FINNAN",
        "aliases": [
          "STEVE FINNAN"
        ],
        "club": null,
        "nationality": "Republic of Ireland",
        "clubs": [
          {
            "club": "Welling United",
            "from": 1993,
            "to": 1995,
            "apps": 41,
            "loan": false
          },
          {
            "club": "Birmingham City",
            "from": 1995,
            "to": 1996,
            "apps": 15,
            "loan": false
          },
          {
            "club": "Notts County",
            "from": 1996,
            "to": 1996,
            "apps": 17,
            "loan": true
          },
          {
            "club": "Notts County",
            "from": 1996,
            "to": 1998,
            "apps": 80,
            "loan": false
          },
          {
            "club": "Fulham",
            "from": 1998,
            "to": 2003,
            "apps": 172,
            "loan": false
          },
          {
            "club": "Liverpool",
            "from": 2003,
            "to": 2008,
            "apps": 145,
            "loan": false
          },
          {
            "club": "Espanyol",
            "from": 2008,
            "to": 2009,
            "apps": 4,
            "loan": false
          },
          {
            "club": "Portsmouth",
            "from": 2009,
            "to": 2010,
            "apps": 21,
            "loan": false
          }
        ],
        "birthYear": 1976,
        "source": "https://en.wikipedia.org/wiki/Steve_Finnan",
        "scramble": "NNAINF",
        "fixed": 0,
        "len": [
          6
        ]
      },
      {
        "id": "s6",
        "band": "b2",
        "x": 0.25,
        "pos": "CM",
        "name": "CAICEDO",
        "display": "MOISES CAICEDO",
        "aliases": [
          "MOISES CAICEDO"
        ],
        "club": null,
        "nationality": "Ecuador",
        "clubs": [
          {
            "club": "Independiente del Valle",
            "from": 2019,
            "to": 2021,
            "apps": 25,
            "loan": false
          },
          {
            "club": "Brighton & Hove Albion",
            "from": 2021,
            "to": 2023,
            "apps": 45,
            "loan": false
          },
          {
            "club": "Beerschot",
            "from": 2021,
            "to": 2022,
            "apps": 12,
            "loan": true
          },
          {
            "club": "Chelsea",
            "from": 2023,
            "to": 2023,
            "apps": 107,
            "loan": false
          }
        ],
        "birthYear": 2001,
        "source": "https://en.wikipedia.org/wiki/Moisés_Caicedo",
        "scramble": "IEAODCC",
        "fixed": 0,
        "len": [
          7
        ]
      },
      {
        "id": "s7",
        "band": "b2",
        "x": 0.5,
        "pos": "CM",
        "name": "JARVIS",
        "display": "MATTHEW JARVIS",
        "aliases": [
          "MATTHEW JARVIS"
        ],
        "club": null,
        "nationality": "England",
        "clubs": [
          {
            "club": "Gillingham",
            "from": 2003,
            "to": 2007,
            "apps": 110,
            "loan": false
          },
          {
            "club": "Wolverhampton Wanderers",
            "from": 2007,
            "to": 2012,
            "apps": 164,
            "loan": false
          },
          {
            "club": "West Ham United",
            "from": 2012,
            "to": 2016,
            "apps": 78,
            "loan": false
          },
          {
            "club": "Norwich City",
            "from": 2015,
            "to": 2016,
            "apps": 5,
            "loan": true
          },
          {
            "club": "Norwich City",
            "from": 2016,
            "to": 2019,
            "apps": 14,
            "loan": false
          },
          {
            "club": "Walsall",
            "from": 2019,
            "to": 2019,
            "apps": 9,
            "loan": true
          },
          {
            "club": "Woking",
            "from": 2020,
            "to": 2021,
            "apps": 23,
            "loan": false
          }
        ],
        "birthYear": 1986,
        "source": "https://en.wikipedia.org/wiki/Matt_Jarvis",
        "scramble": "RIJASV",
        "fixed": 0,
        "len": [
          6
        ]
      },
      {
        "id": "s8",
        "band": "b2",
        "x": 0.75,
        "pos": "CM",
        "name": "MCALLISTER",
        "display": "GARY MCALLISTER",
        "aliases": [
          "GARY MCALLISTER"
        ],
        "club": null,
        "nationality": "Scotland",
        "clubs": [
          {
            "club": "Motherwell",
            "from": 1981,
            "to": 1985,
            "apps": 59,
            "loan": false
          },
          {
            "club": "Leicester City",
            "from": 1985,
            "to": 1990,
            "apps": 201,
            "loan": false
          },
          {
            "club": "Leeds United",
            "from": 1990,
            "to": 1996,
            "apps": 231,
            "loan": false
          },
          {
            "club": "Coventry City",
            "from": 1996,
            "to": 2000,
            "apps": 119,
            "loan": false
          },
          {
            "club": "Liverpool",
            "from": 2000,
            "to": 2002,
            "apps": 55,
            "loan": false
          },
          {
            "club": "Coventry City",
            "from": 2002,
            "to": 2004,
            "apps": 55,
            "loan": false
          }
        ],
        "birthYear": 1964,
        "source": "https://en.wikipedia.org/wiki/Gary_McAllister",
        "scramble": "SAEICTLLRM",
        "fixed": 0,
        "len": [
          10
        ]
      },
      {
        "id": "s9",
        "band": "b3",
        "x": 0.25,
        "pos": "LW",
        "name": "ROY",
        "display": "BRYAN ROY",
        "aliases": [
          "BRYAN ROY"
        ],
        "club": null,
        "nationality": "Netherlands",
        "clubs": [
          {
            "club": "Ajax",
            "from": 1987,
            "to": 1992,
            "apps": 126,
            "loan": false
          },
          {
            "club": "Foggia",
            "from": 1992,
            "to": 1994,
            "apps": 50,
            "loan": false
          },
          {
            "club": "Nottingham Forest",
            "from": 1994,
            "to": 1997,
            "apps": 85,
            "loan": false
          },
          {
            "club": "Hertha BSC",
            "from": 1997,
            "to": 2000,
            "apps": 50,
            "loan": false
          },
          {
            "club": "NAC",
            "from": 2001,
            "to": 2002,
            "apps": 14,
            "loan": false
          }
        ],
        "birthYear": 1970,
        "source": "https://en.wikipedia.org/wiki/Bryan_Roy",
        "scramble": "YRO",
        "fixed": 0,
        "len": [
          3
        ]
      },
      {
        "id": "s10",
        "band": "b3",
        "x": 0.5,
        "pos": "ST",
        "name": "COLE",
        "display": "JOE COLE",
        "aliases": [
          "JOE COLE"
        ],
        "club": null,
        "nationality": "England",
        "clubs": [
          {
            "club": "West Ham United",
            "from": 1998,
            "to": 2003,
            "apps": 126,
            "loan": false
          },
          {
            "club": "Chelsea",
            "from": 2003,
            "to": 2010,
            "apps": 183,
            "loan": false
          },
          {
            "club": "Liverpool",
            "from": 2010,
            "to": 2013,
            "apps": 26,
            "loan": false
          },
          {
            "club": "Lille",
            "from": 2011,
            "to": 2012,
            "apps": 32,
            "loan": true
          },
          {
            "club": "West Ham United",
            "from": 2013,
            "to": 2014,
            "apps": 31,
            "loan": false
          },
          {
            "club": "Aston Villa",
            "from": 2014,
            "to": 2016,
            "apps": 12,
            "loan": false
          },
          {
            "club": "Coventry City",
            "from": 2015,
            "to": 2016,
            "apps": 7,
            "loan": true
          },
          {
            "club": "Coventry City",
            "from": 2016,
            "to": 2016,
            "apps": 15,
            "loan": false
          },
          {
            "club": "Tampa Bay Rowdies",
            "from": 2016,
            "to": 2018,
            "apps": 82,
            "loan": false
          }
        ],
        "birthYear": 1981,
        "source": "https://en.wikipedia.org/wiki/Joe_Cole",
        "scramble": "OCEL",
        "fixed": 0,
        "len": [
          4
        ]
      },
      {
        "id": "s11",
        "band": "b3",
        "x": 0.75,
        "pos": "RW",
        "name": "KUIJT",
        "display": "DIRK KUIJT",
        "aliases": [
          "DIRK KUIJT"
        ],
        "club": null,
        "nationality": "Netherlands",
        "clubs": [
          {
            "club": "Utrecht",
            "from": 1998,
            "to": 2003,
            "apps": 160,
            "loan": false
          },
          {
            "club": "Feyenoord",
            "from": 2003,
            "to": 2006,
            "apps": 101,
            "loan": false
          },
          {
            "club": "Liverpool",
            "from": 2006,
            "to": 2012,
            "apps": 208,
            "loan": false
          },
          {
            "club": "Fenerbahçe",
            "from": 2012,
            "to": 2015,
            "apps": 95,
            "loan": false
          },
          {
            "club": "Feyenoord",
            "from": 2015,
            "to": 2017,
            "apps": 63,
            "loan": false
          }
        ],
        "birthYear": 1980,
        "source": "https://en.wikipedia.org/wiki/Dirk_Kuijt",
        "scramble": "UJTIK",
        "fixed": 0,
        "len": [
          5
        ]
      }
    ]
  }
];
