/* GENERATED by tools/build_clubs.js — do not edit by hand.
 *
 * Every club to have played a Premier League season, from the tables in
 * crossword/js/seasons.js. The crossword derives these from the tables it
 * already loads; the other games load this instead of 64KB of league history
 * to fill one dropdown.
 *
 * Rebuild with:  node tools/build_clubs.js
 */
window.XI_CLUBS = ["AFC Bournemouth","Arsenal","Aston Villa","Barnsley","Birmingham City","Blackburn Rovers","Blackpool","Bolton Wanderers","Bradford City","Brentford","Brighton & Hove Albion","Burnley","Cardiff City","Charlton Athletic","Chelsea","Coventry City","Crystal Palace","Derby County","Everton","Fulham","Huddersfield Town","Hull City","Ipswich Town","Leeds United","Leicester City","Liverpool","Luton Town","Manchester City","Manchester United","Middlesbrough","Newcastle United","Norwich City","Nottingham Forest","Portsmouth","Queens Park Rangers","Reading","Sheffield United","Sheffield Wednesday","Southampton","Stoke City","Sunderland","Swansea City","Tottenham Hotspur","Watford","West Bromwich Albion","West Ham United","Wigan Athletic","Wimbledon","Wolverhampton Wanderers"];
