#!/usr/bin/env node
/* tools/build_puzzles.js
 *
 * Pre-generates puzzles on your machine and writes the SQL to load them into
 * D1. Run it whenever the clue bank changes.
 *
 *   node tools/build_puzzles.js --days 365 --practice 500
 *
 * Why this exists rather than generating on demand: laying out a crossword
 * takes roughly 900ms of CPU and thirty attempts. A Cloudflare Worker is billed
 * and limited on CPU time, and the free plan allows 10ms per request — three
 * orders of magnitude short. Generating here and storing the result turns every
 * request into one indexed SELECT.
 *
 * INPUT  ../pitchword-source/data.json    the private clue bank (never in this repo)
 * OUTPUT data/puzzles-production.sql      gitignored, imported with wrangler
 */
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const HERE = __dirname;
const ROOT = path.join(HERE, "..");

function arg(name, fallback) {
  const i = process.argv.indexOf("--" + name);
  return i === -1 ? fallback : process.argv[i + 1];
}

const DAYS = parseInt(arg("days", "365"), 10);
const PRACTICE = parseInt(arg("practice", "500"), 10);
/* --from N: leave days 1..N-1 exactly as they are and rewrite only from N.
   Once the game is live this is the only safe way to regenerate: a day that
   somebody has already played must not change under them, and a result row
   points at a daily number whose puzzle should still be the one they saw. */
const FROM = Math.max(1, parseInt(arg("from", "1"), 10));
/* Practice is appended by default. Replacing it renumbers the pool, and the
   token a player is mid-puzzle with names a row id — renumbering turns their
   next Check into "that puzzle is no longer stored". */
const REPLACE_PRACTICE = process.argv.includes("--replace-practice");
const RESET = process.argv.includes("--reset");
const SOURCE = arg("source", path.join(ROOT, "..", "crosswordxi-source"));
const OUT = path.join(ROOT, "data", "puzzles-production.sql");
/* The game is called Crossword XI. Eleven is the invariant, not a preference,
   so it is declared before either loop rather than beside the practice pool. */
const TARGET_ANSWERS = 11;
let shortRetries = 0, shortSkipped = 0;

function need(file) {
  const p = path.join(SOURCE, file);
  if (!fs.existsSync(p)) {
    console.error(`\nCannot find ${p}`);
    console.error("Point --source at the folder holding data.json, seasons.json,");
    console.error("daily_bans.json and engine.js (the project archive, kept out of");
    console.error("this repository so the clue bank is never committed).\n");
    process.exit(1);
  }
  return p;
}

const FCW = require(need("engine.js"));
const rows = JSON.parse(fs.readFileSync(need("data.json"), "utf8"));
const bans = JSON.parse(fs.readFileSync(need("daily_bans.json"), "utf8"));

const sqlStr = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const salt = () => crypto.randomBytes(12).toString("hex");

const out = [];
out.push("-- Generated by tools/build_puzzles.js. Do not edit by hand.");
out.push("-- Contains answers: never commit this file.");
if (RESET) {
  out.push("-- --reset: every puzzle replaced. Only safe before launch.");
  out.push("DELETE FROM puzzles;");
} else {
  out.push(`-- Days 1..${FROM - 1} are left untouched.`);
  out.push(`DELETE FROM puzzles WHERE mode = 'daily' AND daily_no >= ${FROM};`);
  if (REPLACE_PRACTICE) out.push("DELETE FROM puzzles WHERE mode = 'practice';");
}

/* Days before FROM are still generated, because each day's bans depend on the
   week before it — the chain cannot be joined halfway. They are computed and
   thrown away; only days from FROM are written. */
/* Two constraints on the daily, both measured over 120 days.

   maxPerFamily — transfers are 63% of the bank, so an unconstrained puzzle drew
   6.3 of its 11 from them, and one drew 9: eleven different answers, but the
   same question asked nine times. Capped at 3.

   DAILY_CLUE_WINDOW — a clue used recently sits out, so the game keeps reaching
   for material it has not used. Coverage over 120 days: 769 clues as it was,
   847 with a 40-day window. Unbounded exclusion reaches 880 but starves the
   pool — 40 of 120 puzzles could not reach eleven answers, so it is a window
   rather than a memory.

   The cost is crossings, 16.8 -> 15.3. Fewer intersections means slightly less
   help from letters already in the grid, which is the price of variety. */
const DAILY_FAMILY_CAP = { Transfer: 3 };
const DAILY_CLUE_WINDOW = 440;
let recentDaily = [];

console.log(`Generating days 1..${DAYS}` +
  (FROM > 1 ? `, writing from ${FROM} (earlier days are recomputed for the ban chain, not written)` : ""));
let t0 = Date.now();
let written = 0;
for (let d = 1; d <= DAYS; d++) {
  const opts = FCW.dailyOptions(d, bans);
  opts.maxPerFamily = DAILY_FAMILY_CAP;
  if (recentDaily.length) {
    const ex = {};
    recentDaily.forEach((id) => { ex[id] = true; });
    const f = Object.assign({}, opts.filter || {}, { excludeIds: ex });
    // Never exclude so much that eleven answers cannot be placed.
    if (FCW.filterViability(rows, f).enough) opts.filter = f;
  }
  const p = FCW.generate(rows, opts);
  p.entries.forEach((e) => recentDaily.push(e.row.id));
  if (recentDaily.length > DAILY_CLUE_WINDOW) {
    recentDaily = recentDaily.slice(-DAILY_CLUE_WINDOW);
  }
  if (p.entries.length !== TARGET_ANSWERS) {
    console.error(`\nDaily #${d} came out with ${p.entries.length} answers, not ${TARGET_ANSWERS}.`);
    console.error("Refusing to write a run with an inconsistent daily.\n");
    process.exit(1);
  }
  if (d >= FROM) {
    const payload = JSON.stringify({ salt: salt(), puzzle: p });
    out.push(`INSERT INTO puzzles (mode, daily_no, category, payload) VALUES ` +
      `('daily', ${d}, NULL, ${sqlStr(payload)});`);
    written++;
  }
  if (d % 25 === 0) console.log(`  ${d}/${DAYS}  (${((Date.now() - t0) / 1000).toFixed(0)}s)`);
}

/* Practice pools, one per topic group plus an unfiltered pool. /api/practice
   accepts ?category=, and /api/categories publishes the list, so the rows have
   to carry a category or the filter matches nothing and every filtered request
   returns 400. The category column is what those queries read. */
const GROUPS = Object.keys(FCW.groupOptions(rows).groups);
const POOLS = [{ category: null, filter: {} },
  ...GROUPS.map((g) => ({ category: g, filter: { groups: [g] } }))];
const perPool = Math.max(1, Math.round(PRACTICE / POOLS.length));

console.log(`Generating ${perPool} practice puzzles for each of ` +
  `${POOLS.length} pools (all${GROUPS.length ? ", " + GROUPS.join(", ") : ""})...`);
t0 = Date.now();
let made = 0;
/* How far back the exclusion reaches. 600 slots covers roughly the last fifty
   puzzles; measured coverage is 851 clues at 200, 977 at 600, and slightly
   worse unbounded — starving the pool makes the generator fall back. */
const RECENT_WINDOW = 600;
let recent = [];
for (const pool of POOLS) {
  // A pool with too few rows cannot make a viable grid; skip it rather than
  // fill the table with failures.
  if (pool.category && !FCW.filterViability(rows, pool.filter).enough) {
    console.log(`  skipping ${pool.category}: not enough rows for a viable grid`);
    continue;
  }
  for (let i = 1; i <= perPool; i++) {
    made++;
    /* Rolling exclusion. Generated independently, every practice puzzle picks
       the same short, easy-fitting rows — 120 puzzles between them used just
       109 distinct clues out of 2,948. Excluding what the last few hundred
       slots used forces the generator down into the rest of the bank, which
       takes the same 120 puzzles to 977 distinct clues. */
    let filter = pool.filter;
    if (recent.length) {
      const ex = {};
      recent.forEach((id) => { ex[id] = true; });
      const candidate = Object.assign({}, pool.filter, { excludeIds: ex });
      // Never exclude so much that the grid cannot be built.
      if (FCW.filterViability(rows, candidate).enough) filter = candidate;
    }
    /* Eleven answers or it does not get stored. generate() returns the best
       layout it found rather than failing, so when the rolling exclusion
       starves the pool it can come back with nine — and two such puzzles went
       into the pool before this check existed. Retry without the exclusion,
       which is always buildable; variety is worth less than the invariant the
       game is named after. */
    let p = FCW.generate(rows, { seed: 1000000 + made * 7919, filter: filter,
                                 maxPerFamily: DAILY_FAMILY_CAP });
    if (p.entries.length !== TARGET_ANSWERS && filter !== pool.filter) {
      p = FCW.generate(rows, { seed: 1000000 + made * 7919, filter: pool.filter,
                               maxPerFamily: DAILY_FAMILY_CAP });
      shortRetries++;
    }
    if (p.entries.length !== TARGET_ANSWERS) {
      shortSkipped++;
      continue;                       // never store a puzzle of the wrong size
    }
    const clueIds = p.entries.map((e) => e.row.id);
    recent.push(...clueIds);
    if (recent.length > RECENT_WINDOW) recent = recent.slice(-RECENT_WINDOW);
    const payload = JSON.stringify({ salt: salt(), category: pool.category, puzzle: p });
    out.push(`INSERT INTO puzzles (mode, daily_no, category, payload, clue_ids) VALUES ` +
      `('practice', NULL, ${pool.category ? sqlStr(pool.category) : "NULL"}, ` +
      `${sqlStr(payload)}, ${sqlStr(JSON.stringify(clueIds))});`);
    if (made % 25 === 0) console.log(`  ${made}  (${((Date.now() - t0) / 1000).toFixed(0)}s)`);
  }
}

fs.writeFileSync(OUT, out.join("\n") + "\n");
const mb = (fs.statSync(OUT).size / 1048576).toFixed(1);
if (shortRetries) console.log(`  ${shortRetries} puzzle(s) rebuilt without the exclusion to reach ${TARGET_ANSWERS}`);
if (shortSkipped) console.log(`  ${shortSkipped} puzzle(s) skipped: could not reach ${TARGET_ANSWERS}`);
console.log(`\nWrote ${OUT}  (${mb}MB, ${written} daily from #${FROM} + ${made} practice)`);
if (!RESET) {
  console.log(`Days 1..${FROM - 1} are untouched; practice is ` +
    (REPLACE_PRACTICE ? "replaced" : "appended, so tokens in play stay valid") + ".");
}
console.log("Import it with:");
console.log("  npx wrangler d1 execute crosswordxi --remote --file=data/puzzles-production.sql\n");
