/* tools/build_clubs.js — the club list every game offers as "Play as".
 *
 *   node tools/build_clubs.js            write shared/xi-clubs.js
 *   node tools/build_clubs.js --check    gate it, write nothing
 *
 * DERIVED, NOT TYPED. The clubs are exactly those that appear in a Premier
 * League table in crossword/js/seasons.js — the same source the crossword's
 * season ladder is drawn from, so a club cannot exist in one place and not the
 * other. Typed out a second time it would be right on the day it was typed.
 *
 * WHY A SEPARATE FILE AT ALL. seasons.js is 64KB of full league tables, which
 * the crossword needs and the other games do not. They need forty-nine names.
 * One derivation, two destinations: the crossword keeps reading the tables,
 * everyone else reads this.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(HERE, "..");
const SRC = path.join(ROOT, "crossword", "js", "seasons.js");
const DEST = path.join(ROOT, "shared", "xi-clubs.js");
const CHECK = process.argv.includes("--check");

/* The file is `var FCW_SEASONS = [...];` and nothing else, so it is read as a
   value rather than executed as a script. */
const src = fs.readFileSync(SRC, "utf8");
const at = src.indexOf("var FCW_SEASONS = ");
if (at < 0) {
  console.error("\nseasons.js does not start with var FCW_SEASONS. Nothing written.\n");
  process.exit(1);
}
const json = src.slice(at + "var FCW_SEASONS = ".length, src.lastIndexOf("];") + 1);
const seasons = JSON.parse(json);

const seen = new Set();
for (const s of seasons) for (const r of s.table || []) if (r.club) seen.add(r.club);
const clubs = [...seen].sort();
if (clubs.length < 40) {
  console.error(`\nOnly ${clubs.length} clubs found — the tables did not parse as expected.\n`);
  process.exit(1);
}

const out = `/* GENERATED by tools/build_clubs.js — do not edit by hand.
 *
 * Every club to have played a Premier League season, from the tables in
 * crossword/js/seasons.js. The crossword derives these from the tables it
 * already loads; the other games load this instead of 64KB of league history
 * to fill one dropdown.
 *
 * Rebuild with:  node tools/build_clubs.js
 */
window.XI_CLUBS = ${JSON.stringify(clubs, null, 0)};
`;

if (CHECK) {
  const stored = fs.existsSync(DEST) ? fs.readFileSync(DEST, "utf8") : "";
  if (stored !== out) {
    console.error(`\nshared/xi-clubs.js is NOT what seasons.js produces.` +
      `\nRun: node tools/build_clubs.js\n`);
    process.exit(1);
  }
  console.log(`\n${clubs.length} clubs, and the stored list matches. Nothing written.\n`);
  process.exit(0);
}

fs.writeFileSync(DEST, out);
console.log(`\n${clubs.length} clubs written to shared/xi-clubs.js\n`);
