#!/usr/bin/env node
/* tools/build_puzzles.js
 *
 * Pre-generates puzzles on your machine and writes the SQL to load them into
 * D1. Run it whenever the clue bank changes.
 *
 *   node tools/build_puzzles.js --days 365 --practice 500
 *
 * Why this exists rather than generating on demand: laying out a crossword
 * takes roughly 900ms of CPU and thirty attempts. A Cloudflare Worker is billed
 * and limited on CPU time, and the free plan allows 10ms per request — three
 * orders of magnitude short. Generating here and storing the result turns every
 * request into one indexed SELECT.
 *
 * INPUT  ../pitchword-source/data.json    the private clue bank (never in this repo)
 * OUTPUT data/puzzles-production.sql      gitignored, imported with wrangler
 */
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const HERE = __dirname;
const ROOT = path.join(HERE, "..");

function arg(name, fallback) {
  const i = process.argv.indexOf("--" + name);
  return i === -1 ? fallback : process.argv[i + 1];
}

const DAYS = parseInt(arg("days", "365"), 10);
const PRACTICE = parseInt(arg("practice", "500"), 10);
const SOURCE = arg("source", path.join(ROOT, "..", "crosswordxi-source"));
const OUT = path.join(ROOT, "data", "puzzles-production.sql");

function need(file) {
  const p = path.join(SOURCE, file);
  if (!fs.existsSync(p)) {
    console.error(`\nCannot find ${p}`);
    console.error("Point --source at the folder holding data.json, seasons.json,");
    console.error("daily_bans.json and engine.js (the project archive, kept out of");
    console.error("this repository so the clue bank is never committed).\n");
    process.exit(1);
  }
  return p;
}

const FCW = require(need("engine.js"));
const rows = JSON.parse(fs.readFileSync(need("data.json"), "utf8"));
const bans = JSON.parse(fs.readFileSync(need("daily_bans.json"), "utf8"));

const sqlStr = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const salt = () => crypto.randomBytes(12).toString("hex");

const out = [];
out.push("-- Generated by tools/build_puzzles.js. Do not edit by hand.");
out.push("-- Contains answers: never commit this file.");
out.push("DELETE FROM puzzles;");

console.log(`Generating ${DAYS} daily puzzles...`);
let t0 = Date.now();
for (let d = 1; d <= DAYS; d++) {
  const p = FCW.generate(rows, FCW.dailyOptions(d, bans));
  const payload = JSON.stringify({ salt: salt(), puzzle: p });
  out.push(`INSERT INTO puzzles (mode, daily_no, category, payload) VALUES ` +
    `('daily', ${d}, NULL, ${sqlStr(payload)});`);
  if (d % 25 === 0) console.log(`  ${d}/${DAYS}  (${((Date.now() - t0) / 1000).toFixed(0)}s)`);
}

/* Practice pools, one per topic group plus an unfiltered pool. /api/practice
   accepts ?category=, and /api/categories publishes the list, so the rows have
   to carry a category or the filter matches nothing and every filtered request
   returns 400. The category column is what those queries read. */
const GROUPS = Object.keys(FCW.groupOptions(rows).groups);
const POOLS = [{ category: null, filter: {} },
  ...GROUPS.map((g) => ({ category: g, filter: { groups: [g] } }))];
const perPool = Math.max(1, Math.round(PRACTICE / POOLS.length));

console.log(`Generating ${perPool} practice puzzles for each of ` +
  `${POOLS.length} pools (all${GROUPS.length ? ", " + GROUPS.join(", ") : ""})...`);
t0 = Date.now();
let made = 0;
for (const pool of POOLS) {
  // A pool with too few rows cannot make a viable grid; skip it rather than
  // fill the table with failures.
  if (pool.category && !FCW.filterViability(rows, pool.filter).enough) {
    console.log(`  skipping ${pool.category}: not enough rows for a viable grid`);
    continue;
  }
  for (let i = 1; i <= perPool; i++) {
    made++;
    // Practice is unseeded variety, not a shared puzzle, so any seed will do.
    const p = FCW.generate(rows, { seed: 1000000 + made * 7919, filter: pool.filter });
    const payload = JSON.stringify({ salt: salt(), category: pool.category, puzzle: p });
    out.push(`INSERT INTO puzzles (mode, daily_no, category, payload) VALUES ` +
      `('practice', NULL, ${pool.category ? sqlStr(pool.category) : "NULL"}, ${sqlStr(payload)});`);
    if (made % 25 === 0) console.log(`  ${made}  (${((Date.now() - t0) / 1000).toFixed(0)}s)`);
  }
}

fs.writeFileSync(OUT, out.join("\n") + "\n");
const mb = (fs.statSync(OUT).size / 1048576).toFixed(1);
console.log(`\nWrote ${OUT}  (${mb}MB, ${DAYS} daily + ${made} practice)`);
console.log("Import it with:");
console.log("  npx wrangler d1 execute crosswordxi --remote --file=data/puzzles-production.sql\n");
