#!/usr/bin/env node
/* tools/import_clues.js — turns the private clue bank into SQL for D1.
 *
 *   node tools/import_clues.js --source ../crosswordxi-source
 *
 * OUTPUT data/clues-production.sql   gitignored: it contains every answer.
 */
const fs = require("fs"), path = require("path");
const i = process.argv.indexOf("--source");
const SOURCE = i === -1 ? path.join(__dirname, "..", "..", "crosswordxi-source") : process.argv[i + 1];
const src = path.join(SOURCE, "data.json");
if (!fs.existsSync(src)) {
  console.error(`\nCannot find ${src}\nPoint --source at the folder holding data.json.\n`);
  process.exit(1);
}
const rows = JSON.parse(fs.readFileSync(src, "utf8"));
const q = (v) => (v === null || v === undefined || v === "" ? "NULL" : "'" + String(v).replace(/'/g, "''") + "'");
const n = (v) => (v === null || v === undefined || v === "" ? "NULL" : Number(v));

const out = ["-- Generated by tools/import_clues.js. Contains answers: never commit.", "DELETE FROM clues;"];
for (const r of rows) {
  out.push("INSERT INTO clues (id, category, clue, answer, grid, enumeration, entity, " +
    "difficulty, era, puzzle_group, max_per, active, notes) VALUES (" +
    [q(r.id), q(r.cat), q(r.clue), q(r.answer), q(r.grid), q(r.enum), q(r.entity),
     n(r.diff), q(r.era), q(r.pgk), r.maxPer === 0 ? 0 : n(r.maxPer) ?? 1,
     r.maxPer === 0 ? 0 : 1, q(r.notes)].join(", ") + ");");
}
const dest = path.join(__dirname, "..", "data", "clues-production.sql");
fs.writeFileSync(dest, out.join("\n") + "\n");
console.log(`Wrote ${dest}  (${rows.length} clues, ${(fs.statSync(dest).size / 1048576).toFixed(1)}MB)`);
console.log("Import with:\n  npx wrangler d1 execute crosswordxi --remote --file=data/clues-production.sql\n");
