#!/usr/bin/env node
/* tools/import_scrambled.js — the boards into SQL for D1.
 *
 *   node tools/import_scrambled.js
 *   npx wrangler d1 execute crosswordxi --remote --file=data/sc-production.sql
 *
 * OUTPUT data/sc-production.sql   gitignored by data/*-production.sql: it
 *                                 contains every name on every board.
 *
 * IT TRANSPORTS, IT DOES NOT DERIVE. The boards are built by
 * tools/build_scrambled.js from tools/scrambled/xi/*.json, and this reads the
 * module that build produced. Re-deriving them here would be a second
 * implementation of scrambling, formation parsing and slot ids — and the two
 * would drift the first time either changed. One derivation, two destinations:
 * the module the Worker falls back to, and the rows it prefers.
 *
 * AND IT REFUSES IF THE MODULE IS STALE. `build_scrambled.js --check` proves
 * the stored module is what the sources produce. If someone hand-edited the
 * module, or edited an XI without rebuilding, importing would put that
 * difference into the database where no gate can see it. So the check runs
 * first and nothing is written when it fails.
 */
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "data", "sc-production.sql");

/* The gate first. Its failure is this tool's failure. */
try {
  execFileSync(process.execPath, [path.join(ROOT, "tools", "build_scrambled.js"), "--check"],
    { cwd: ROOT, stdio: ["ignore", "pipe", "pipe"] });
} catch (e) {
  console.error("REFUSED: tools/build_scrambled.js --check did not pass.");
  console.error("The stored module is not what the sources produce. Run");
  console.error("  node tools/build_scrambled.js");
  console.error("and look at what changed before importing anything.");
  process.exit(1);
}

const { SC_BOARDS } = await import(
  "file://" + path.join(ROOT, "functions", "_lib", "sc-boards.js").split(path.sep).join("/"));

if (!Array.isArray(SC_BOARDS) || !SC_BOARDS.length) {
  console.error("REFUSED: the generated module holds no boards.");
  process.exit(1);
}

/* Every board must name its source. The builder already refuses one without,
   so this cannot fire — which is the point of asserting it anyway: the day the
   builder's rule is relaxed, the database stops being able to say where a
   claim came from, and that should be a refusal here too rather than a silent
   NULL. */
for (const b of SC_BOARDS) {
  if (!b.source) { console.error(`REFUSED: board ${b.id} has no source URL.`); process.exit(1); }
  if (!b.title) { console.error(`REFUSED: board ${b.id} has no title.`); process.exit(1); }
}

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const now = new Date().toISOString();
const lines = [
  "-- GENERATED by tools/import_scrambled.js — do not edit.",
  "-- Contains every name on every board. Gitignored.",
  "-- Apply migration 023-scrambled-boards.sql first.",
  "",
  "DELETE FROM sc_board;",
  "",
];
for (const b of SC_BOARDS) {
  lines.push(
    "INSERT INTO sc_board (id, title, payload, source, updated_at) VALUES (" +
    [b.id, q(b.title), q(JSON.stringify(b)), q(b.source), q(now)].join(", ") + ");");
}
lines.push("");

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, lines.join("\n"));

const names = SC_BOARDS.reduce((n, b) => n + (b.slots || []).length, 0);
console.log(`${SC_BOARDS.length} board(s), ${names} names -> data/sc-production.sql`);
console.log("\nApply with:\n  npx wrangler d1 execute crosswordxi --remote --file=data/migrations/023-scrambled-boards.sql");
console.log("  npx wrangler d1 execute crosswordxi --remote --file=data/sc-production.sql\n");
